Repository web-infra-dev/midscene, pull requests merged in 2024-12, with the labels that each got.

#175 feat: support socks proxy for OpenAI SDK
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/midscene/package.json
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/env.ts
  packages/midscene/src/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#176 fix: sandbox issue of puppeteer in Ubuntu
  apps/site/docs/zh/index.mdx
  packages/cli/src/yaml-player.ts
  packages/visualizer/unpacked-extension/manifest.json
  packages/web-integration/tests/ai/web/puppeteer/utils.ts
Labels: change: fix

#182 fix: test case
  packages/midscene/tests/ai/inspect.test.ts
Labels: change: fix

#187 feat: support more model
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  apps/site/rspress.config.ts
  packages/midscene/src/ai-model/automation/index.ts
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/tests/ai/evaluate/__snapshots__/planning.test.ts.snap
  packages/midscene/tests/ai/evaluate/planning.test.ts
  packages/midscene/tests/ai/openai.test.ts
Labels: change: feat

#184 feat: support the if-statement in planning prompt
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  apps/site/rspress.config.ts
  packages/midscene/src/ai-model/automation/index.ts
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/types.ts
  packages/midscene/tests/ai/evaluate/__snapshots__/planning.test.ts.snap
  packages/midscene/tests/ai/evaluate/planning.test.ts
  packages/midscene/tests/ai/openai.test.ts
  packages/visualizer/src/component/replay-scripts.tsx
  packages/web-integration/src/appium/page.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/web/puppeteer/scroll.html
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/unit-test/web-extractor.test.ts
Labels: change: feat

#190 docs: add docs for customize model and endpoint
  .vscode/settings.json
  README.ja.md
  README.md
  README.zh.md
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/index.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/model-provider.md
  apps/site/docs/zh/quick-experience.mdx
  apps/site/rspress.config.ts
  packages/midscene/tests/ai/evaluate/planning.test.ts
Labels: change: docs

#197 feat: invoke anthropic SDK to call Claude
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/midscene/package.json
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/env.ts
  packages/midscene/tests/ai/connectivity.test.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/puppeteer/page.ts
  pnpm-lock.yaml
Labels: change: feat

#194 fix: fix scroll action in chrome extension
  apps/site/docs/zh/index.mdx
  packages/web-integration/src/appium/page.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#201 fix: keypress issue in chrome extension
  apps/site/docs/en/index.mdx
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/model-provider.md
  packages/midscene/tests/ai/connectivity.test.ts
  packages/web-integration/src/chrome-extension/USKeyboardLayout.ts
  packages/web-integration/src/chrome-extension/cdpInput.ts
  packages/web-integration/src/chrome-extension/page.ts
Labels: change: fix

#204 fix: unescaped scripts in report tpl
  packages/midscene/src/utils.ts
  packages/visualizer/html/extension-sidepanel.html
  packages/visualizer/html/report.html
  packages/visualizer/scripts/build-html.ts
Labels: change: fix

#206 fix: adjust the prompt to fit the non-described text
  packages/midscene/src/ai-model/prompt/util.ts
Labels: change: fix

#208 fix: make puppeteer external in web-integration
  packages/cli/src/printer.ts
  packages/cli/src/yaml-runner.ts
  packages/web-integration/modern.config.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: fix

#210 fix: show error message when aiAction fails in extension
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/zh/quick-experience.mdx
  packages/visualizer/src/component/playground-component.tsx
Labels: change: fix

#212 feat: let max_tokens configurable
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/env.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: feat

#218 docs: add lark link
  README.md
  README.zh.md
  apps/site/rspress.config.ts
Labels: change: docs

#219 fix: remove scripting permission from manifest
  packages/visualizer/unpacked-extension/manifest.json
Labels: change: fix

#223 fix: typo in model name
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
Labels: change: fix

#227 feat: support keyless auth mode for azure
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/env.ts
Labels: change: feat
