Repository web-infra-dev/midscene, pull requests merged in 2024-11, with the labels that each got.

#144 feat: optimize the speed of screenshot in browser
  packages/midscene/src/types.ts
  packages/shared/src/img/box-select.ts
  packages/shared/src/img/info.ts
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/playground-component.tsx
  packages/web-integration/src/appium/page.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/unit-test/web-extractor.test.ts
Labels: change: feat

#145 docs: optimize description
  apps/site/rspress.config.ts
  packages/visualizer/unpacked-extension/manifest.json
Labels: change: docs

#148 feat(cache): optimize cache logic id and export overrideAIConfig
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/puppeteer/index.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: feat

#149 docs: add introduction to our Chrome extension
  apps/site/docs/en/API.md
  apps/site/docs/en/_meta.json
  apps/site/docs/en/cache.md
  apps/site/docs/en/cli.md
  apps/site/docs/en/docs/_meta.json
  apps/site/docs/en/docs/getting-started/_meta.json
  apps/site/docs/en/docs/getting-started/demo.md
  apps/site/docs/en/docs/getting-started/introduction.mdx
  apps/site/docs/en/docs/getting-started/quick-start.mdx
  apps/site/docs/en/docs/more/_meta.json
  apps/site/docs/en/docs/usage/_meta.json
  apps/site/docs/en/faq.md
  apps/site/docs/en/index.md
  apps/site/docs/en/index.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/zh/API.md
  apps/site/docs/zh/_meta.json
  apps/site/docs/zh/cache.md
  apps/site/docs/zh/cli.md
  apps/site/docs/zh/docs/_meta.json
  apps/site/docs/zh/docs/getting-started/_meta.json
  apps/site/docs/zh/docs/getting-started/demo.md
  apps/site/docs/zh/docs/getting-started/introduction.mdx
  apps/site/docs/zh/docs/getting-started/quick-start.mdx
  apps/site/docs/zh/docs/more/_meta.json
  apps/site/docs/zh/docs/usage/_meta.json
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/index.md
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/model-provider.md
  apps/site/docs/zh/prompting-tips.md
  apps/site/docs/zh/quick-experience.mdx
  apps/site/rspress.config.ts
  apps/site/theme/index.tsx
  packages/cli/src/help.ts
Labels: change: docs

#150 feat: add screenshot for extension document
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/public/midscene-extension.jpg
  apps/site/docs/zh/quick-experience.mdx
  packages/visualizer/src/component/open-in-playground.tsx
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/component/store.tsx
Labels: change: feat

#151 fix: links in readme
  README.ja.md
  README.md
  README.zh.md
Labels: change: fix

#153 feat: add static-server into cli
  apps/site/docs/en/cli.md
  apps/site/docs/zh/cli.md
  package.json
  packages/cli/bin/midscene
  packages/cli/modern.config.ts
  packages/cli/package.json
  packages/cli/src/args.ts
  packages/cli/src/help.ts
  packages/cli/src/http-server.d.ts
  packages/cli/src/index.ts
  packages/cli/src/playground.ts
  packages/cli/tests/args.test.ts
  packages/cli/tests/bin.test.ts
  packages/cli/tests/server_root/index.html
  packages/visualizer/.gitignore
  packages/visualizer/package.json
  packages/visualizer/scripts/check-html.sh
  pnpm-lock.yaml
Labels: change: feat

#154 workflow(ci): AI test cases
  README.ja.md
  README.md
  README.zh.md
  packages/web-integration/tests/ai/web/static/static-page.test.ts
Labels: change: fix

#164 feat: 修改 .cli 404 路径
  apps/site/docs/zh/index.mdx
Labels: change: feat

#159 feat: lower the cost of page description
  .github/workflows/ai.yml
  packages/midscene/src/ai-model/prompt/element_inspector.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/types.ts
  packages/midscene/tests/unit-test/prompt/utils.test.ts
  packages/web-integration/src/extractor/util.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/unit-test/__snapshots__/client-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/__snapshots__/web-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/scroll/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/scroll/output.png
Labels: change: feat

#168 feat(core): Enhance environment logic and introduce MIDSCENE_REPORT_TAG_NAME for customizable report name prefixes
  packages/midscene/modern.config.ts
  packages/midscene/package.json
  packages/midscene/src/action/executor.ts
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/ai-model/prompt/element_inspector.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/env.ts
  packages/midscene/src/index.ts
  packages/midscene/src/insight/utils.ts
  packages/midscene/src/utils.ts
  packages/web-integration/src/common/utils.ts
Labels: change: feat

#169 fix: tooltip of env config
  packages/visualizer/src/component/env-config.tsx
Labels: change: fix

#170 feat: dump LLM usage info
  packages/midscene/src/ai-model/automation/index.ts
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/insight/index.ts
  packages/midscene/src/types.ts
  packages/visualizer/src/component/detail-side.tsx
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#172 feat: simplify planning response
  .github/workflows/ai.yml
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  packages/midscene/src/ai-model/automation/index.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/types.ts
  packages/visualizer/src/component/detail-side.tsx
  packages/visualizer/src/utils.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/ai/web/puppeteer/utils.ts
Labels: change: feat

#173 fix: add link to yaml doc in Chinese
  apps/site/rspress.config.ts
Labels: change: fix
