Repository web-infra-dev/midscene, pull requests merged in 2024-10, with the labels that each got.

#102 docs: add Japanese README
  README.ja.md
  README.md
  README.zh.md
Labels: change: docs

#103 feat: implement a better replay widget on the report page
  packages/visualizer/src/component/detail-panel.tsx
  packages/visualizer/src/component/player.less
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/replay-scripts.tsx
  packages/visualizer/src/component/store.tsx
  packages/visualizer/src/index.less
  packages/visualizer/src/index.tsx
Labels: change: feat

#108 fix: adjust the model evaluation
  package.json
  packages/midscene/package.json
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/ai-model/prompt/element_inspector.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/insight/index.ts
  packages/midscene/tests/ai/evaluate/ai-data/inspect/aweme_login.json
  packages/midscene/tests/ai/evaluate/ai-data/inspect/aweme_play.json
  packages/midscene/tests/ai/evaluate/inspect.test.ts
  packages/midscene/tests/ai/evaluate/test-data/aweme-login/element-snapshot.json
  packages/midscene/tests/ai/evaluate/test-data/aweme-login/input.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-login/output.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-login/output_without_text.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-login/resize-output.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-play/element-snapshot.json
  packages/midscene/tests/ai/evaluate/test-data/aweme-play/input.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-play/output.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-play/output_without_text.png
  packages/midscene/tests/ai/evaluate/test-data/aweme-play/resize-output.png
  packages/midscene/tests/ai/evaluate/test-suite/test-analyzer.ts
  packages/midscene/tests/ai/evaluate/test-suite/util.ts
  packages/shared/src/img/box-select.ts
  packages/web-integration/tests/ai/web/playwright/generate-test-data.spec.ts
Labels: change: fix

#105 docs: update docs
  CONTRIBUTING.md
  apps/site/docs/en/docs/getting-started/quick-start.mdx
  apps/site/docs/en/docs/more/prompting-tips.md
  apps/site/docs/en/docs/usage/API.md
Labels: change: docs

#114 fix(ai-model): optimize ai model prompt
  packages/midscene/src/ai-model/prompt/element_inspector.ts
  packages/midscene/tests/ai/util.ts
Labels: change: fix

#115 feat: add a button for replay-all in report page
  packages/visualizer/src/component/common.less
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/replay-scripts.tsx
  packages/visualizer/src/component/sidebar.tsx
  packages/visualizer/src/component/store.tsx
  packages/visualizer/src/index.less
  packages/visualizer/src/index.tsx
Labels: change: feat

#120 docs(readme): adjusted commas and semicolons in README.md
  README.md
Labels: change: docs

#117 fix(ai-model): optimize inspect element prompt
  packages/midscene/src/ai-model/prompt/element_inspector.ts
  packages/midscene/tests/ai/evaluate/ai-data/inspect/taobao.json
  packages/midscene/tests/ai/evaluate/inspect.test.ts
  packages/midscene/tests/ai/evaluate/test-suite/test-analyzer.ts
Labels: change: fix

#122 docs: add repository and homepage in package.json
  packages/cli/package.json
  packages/midscene/package.json
  packages/shared/package.json
  packages/visualizer/package.json
  packages/web-integration/package.json
Labels: change: feat

#129 fix: fix the Player style when the locator is failed
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/types.ts
  packages/midscene/src/utils.ts
  packages/visualizer/scripts/build-html.ts
  packages/visualizer/src/component/blackboard.tsx
  packages/visualizer/src/component/player.less
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/replay-scripts.tsx
  packages/visualizer/src/component/store.tsx
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/extractor/client-extractor.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: fix

#127 docs(homepage): Fixed the Footer
  apps/site/rspress.config.ts
  apps/site/styles/index.css
Labels: change: docs

#137 fix: .aiAction fail to run in Playwright
  packages/web-integration/src/playwright/ai-fixture.ts
Labels: change: fix

#138 feat: add chrome extension building script
  biome.json
  packages/visualizer/.gitignore
  packages/visualizer/build-extension.sh
  packages/visualizer/html/playground.html
  packages/visualizer/modern.config.ts
  packages/visualizer/package.json
  packages/visualizer/scripts/build-html.ts
  packages/visualizer/src/component/blackboard.tsx
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/extension/playground-entry.ts
  packages/visualizer/src/extension/popup.ts
  packages/visualizer/src/extension/utils.ts
  packages/visualizer/src/extension/worker.ts
  packages/visualizer/unpacked-extension/icon.png
  packages/visualizer/unpacked-extension/manifest.json
  packages/visualizer/unpacked-extension/popup.html
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: change: feat

#141 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: change: docs
