Repository web-infra-dev/midscene, pull requests merged in 2025-01, with the labels that each got.

#233 fix: add some default value for tmp dir #231
  packages/shared/src/fs/index.ts
Labels: change: fix

#232 fix: use some default param in scroll
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
Labels: change: fix

#235 docs: update video url and update slogn
  README.md
  README.zh.md
  apps/site/docs/en/index.mdx
  apps/site/rspress.config.ts
Labels: change: docs

#236 docs: update the midscene introduction
  apps/site/rspress.config.ts
  packages/midscene/README.md
  packages/midscene/package.json
  packages/web-integration/README.md
  packages/web-integration/package.json
Labels: change: docs

#230 feat(ai-model): support Image positioning and integrate langchain
  packages/midscene/package.json
  packages/midscene/src/ai-model/automation.ts
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/ai-model/prompt/element_inspector.ts
  packages/midscene/src/ai-model/prompt/element_point.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/env.ts
  packages/midscene/src/types.ts
  packages/midscene/tests/ai/evaluate/__snapshots__/planning-input.test.ts.snap
  packages/midscene/tests/ai/extract/__snapshots__/extract.test.ts.snap
  packages/midscene/tests/ai/inspect.test.ts
  packages/midscene/tests/ai/inspect2.test.ts
  packages/midscene/tests/ai/prompt.test.ts
  packages/midscene/tests/unit-test/prompt/utils.test.ts
  packages/midscene/tests/unit-test/utils.test.ts
  packages/shared/src/img/draw-box.ts
  packages/shared/src/img/index.ts
  packages/visualizer/modern.config.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/ai/web/playwright/ai-online-order.spec.ts
  pnpm-lock.yaml
Labels: change: feat

#238 fix(prompt): fix plan prompt and optimize task background content
  packages/midscene/src/ai-model/automation.ts
  packages/midscene/src/ai-model/prompt/planning.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/env.ts
Labels: change: fix

#239 fix(prompt): optimize plan prompt
  packages/midscene/src/ai-model/prompt/planning.ts
Labels: change: fix

#246 fix: allow using claude in extension #241
  packages/midscene/src/ai-model/openai/index.ts
Labels: change: fix

#228 feat: add bridge mode for extension
  README.md
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/index.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/public/midscene-bridge-mode.jpg
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/model-provider.md
  apps/site/rspress.config.ts
  nx.json
  packages/midscene/package.json
  packages/midscene/src/action/executor.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/insight/index.ts
  packages/visualizer/modern.config.ts
  packages/visualizer/package.json
  packages/visualizer/src/component/common.less
  packages/visualizer/src/component/env-config.tsx
  packages/visualizer/src/component/logo.less
  packages/visualizer/src/component/logo.tsx
  packages/visualizer/src/component/misc.tsx
  packages/visualizer/src/component/playground-component.less
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/component/store.tsx
  packages/visualizer/src/extension/bridge.less
  packages/visualizer/src/extension/bridge.tsx
  packages/visualizer/src/extension/playground-entry.tsx
  packages/visualizer/src/extension/popup.less
  packages/visualizer/src/extension/popup.tsx
  packages/visualizer/src/index.tsx
  packages/visualizer/src/init.ts
  packages/web-integration/modern.config.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/browser.ts
  packages/web-integration/src/bridge-mode/common.ts
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/bridge-mode/io-client.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/extractor/web-extractor.ts
  packages/web-integration/src/page.ts
  packages/web-integration/tests/ai/bridge/agent.test.ts
  packages/web-integration/tests/ai/web/playwright/todo-app-midscene.spec.ts
  packages/web-integration/tests/unit-test/bridge/io.test.ts
  packages/web-integration/vitest.config.ts
  pnpm-lock.yaml
Labels: change: feat

#251 fix: yaml scripts issue in windows
  packages/cli/src/cli-utils.ts
  packages/cli/src/index.ts
  packages/cli/src/printer.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: fix

#255 fix: lazy close for puppeteer in windows
  packages/cli/src/cli-utils.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: fix

#226 feat: add environment variable interpolation to YAML script parser
  packages/web-integration/src/yaml/utils.ts
  packages/web-integration/tests/unit-test/yaml/utils.test.ts
Labels: change: feat

#260 fix: a more friendly error code for extension
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/component/store.tsx
  packages/visualizer/src/extension/popup.tsx
  packages/visualizer/unpacked-extension/manifest.json
  packages/web-integration/src/chrome-extension/page.ts
Labels: change: fix

#262 feat(ai-model): support ai to target
  packages/midscene/modern.config.ts
  packages/midscene/package.json
  packages/midscene/src/action/executor.ts
  packages/midscene/src/ai-model/index.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/openai/index.ts
  packages/midscene/src/ai-model/prompt/element-inspector.ts
  packages/midscene/src/ai-model/prompt/element-point.ts
  packages/midscene/src/ai-model/prompt/element_point.ts
  packages/midscene/src/ai-model/prompt/ui-tars-planing.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/src/ai-model/vlm-planing.ts
  packages/midscene/src/env.ts
  packages/midscene/src/index.ts
  packages/midscene/src/insight/index.ts
  packages/midscene/src/types.ts
  packages/midscene/tests/ai/evaluate/test-suite/util.ts
  packages/midscene/tests/ai/parse-action.test.ts
  packages/midscene/tests/ai/plan/output.png
  packages/midscene/tests/ai/plan/plan-to-target.test.ts
  packages/shared/package.json
  packages/shared/src/constants/index.ts
  packages/shared/src/utils.ts
  packages/visualizer/src/component/detail-side.tsx
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/extension/popup.tsx
  packages/web-integration/modern.config.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/extractor/util.ts
  packages/web-integration/src/extractor/web-extractor.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/puppeteer/index.ts
  packages/web-integration/tests/ai/web/playwright/plan-to-target/new-ai.spec.ts
  packages/web-integration/tests/unit-test/__snapshots__/client-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/scroll/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/scroll/output.png
  pnpm-lock.yaml
Labels: change: feat

#270 feat: add more social links
  README.md
  README.zh.md
  apps/site/rspress.config.ts
Labels: change: feat

#272 feat: allow tracking newly-opened tabs in Chrome extension
  apps/site/docs/en/API.md
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/index.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/zh/API.md
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/model-provider.md
  packages/midscene/src/ai-model/automation.ts
  packages/visualizer/src/component/playground-component.less
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/component/store.tsx
  packages/visualizer/src/extension/popup.tsx
  packages/visualizer/src/extension/utils.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#271 feat(chrome-devtool): water flow animation on the target page
  packages/midscene/src/action/executor.ts
  packages/visualizer/modern.config.ts
  packages/visualizer/src/extension/scripts/stop-water-flow.ts
  packages/visualizer/src/extension/scripts/water-flow.ts
  packages/web-integration/src/chrome-extension/dynamic-scripts.ts
  packages/web-integration/src/chrome-extension/page.ts
Labels: change: feat

#280 fix(extract-data): resolve match multiple element
  packages/midscene/src/ai-model/prompt/ui-tars-planning.ts
  packages/midscene/src/ai-model/prompt/util.ts
  packages/midscene/tests/ai/parse-action.test.ts
  packages/midscene/tsconfig.json
Labels: change: fix

#281 feat(chrome-devtool): add 'stop' button in extension
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/extension/popup.tsx
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#282 feat(chrome-devtool): allow tracking active tab in bridge mode
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/common.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/tests/ai/bridge/agent.test.ts
Labels: change: feat

#301 feat: use jpeg as default image format
  packages/midscene/src/utils.ts
  packages/shared/src/img/box-select.ts
  packages/shared/src/img/draw-box.ts
  packages/shared/src/img/transform.ts
  packages/visualizer/scripts/build-html.ts
  packages/visualizer/src/component/playground-component.tsx
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: feat

#303 fix: bing-search.yaml add tasks
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
Labels: change: fix

#304 fix(action): keyboard and div extracting
  packages/cli/src/index.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/extractor/util.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/web/playwright/ai-auto-todo.spec.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/unit-test/__snapshots__/web-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/fixtures/web-extractor/index.html
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
Labels: change: fix

#305 docs(ai-model): update docs for ui-tars
  README.md
  README.zh.md
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/choose-a-model.mdx
  apps/site/docs/en/index.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/choose-a-model.mdx
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/model-provider.md
  apps/site/docs/zh/prompting-tips.md
  apps/site/rspress.config.ts
  apps/site/styles/index.css
  packages/web-integration/tests/unit-test/web-extractor.test.ts
Labels: change: docs

#307 fix(e2e): optimize e2e error
  .github/workflows/ai.yml
  packages/web-integration/tests/ai/web/playwright/plan-to-target/new-ai.spec.ts
Labels: change: fix

#308 docs: update comparing section
  README.md
  README.zh.md
  apps/site/docs/en/index.mdx
  apps/site/docs/zh/index.mdx
Labels: change: docs

#311 docs: update wording in index.mdx
  apps/site/docs/en/index.mdx
Labels: change: docs

#317 docs: update discord link
  README.md
  README.zh.md
  apps/site/docs/en/index.mdx
  apps/site/docs/zh/index.mdx
  apps/site/rspress.config.ts
Labels: change: docs

#318 docs: add example video description
  README.md
  README.zh.md
Labels: change: docs

#325 docs: optimize docs and fix ai test
  README.md
  README.zh.md
  packages/midscene/tests/ai/evaluate/assertion.test.ts
Labels: change: docs

#327 docs: fix citation format
  README.md
  README.zh.md
Labels: change: docs

#321 feat(browser-event): support drag event
  packages/midscene/src/ai-model/ui-tars-planning.ts
  packages/midscene/src/types.ts
  packages/web-integration/package.json
  packages/web-integration/src/appium/page.ts
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/common.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/bridge/temp.test.ts
Labels: change: feat

#329 docs: add comparison for different model
  apps/site/docs/en/caching.md
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/faq.md
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/public/midescene-playground-entry.jpg
  apps/site/docs/zh/caching.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/prompting-tips.md
  apps/site/rspress.config.ts
Labels: change: docs

#310 feat(puppeteer): allow tracking new tab in puppeteer agent
  .vscode/settings.json
  apps/site/docs/en/API.md
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/zh/API.md
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  packages/midscene/src/yaml.d.ts
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/src/puppeteer/index.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/ai/web/puppeteer/utils.ts
  packages/web-integration/tests/unit-test/playground-server.test.ts
Labels: change: feat

#330 feat(ui-tars): enhance the UI-TARS keyboard event handling and optimize parser logic
  packages/midscene/package.json
  packages/midscene/src/ai-model/prompt/ui-tars-planning.ts
  packages/midscene/src/ai-model/ui-tars-planning.ts
  packages/midscene/tests/ai/parse-action.test.ts
  packages/midscene/tests/ai/plan/plan-to-target.test.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  packages/shared/src/us-keyboard-layout.ts
  packages/shared/tests/unit-test/image/__snapshots__/index.test.ts.snap
  packages/shared/tests/unit-test/keyboard.test.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/cdpInput.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/bridge/agent.test.ts
  packages/web-integration/tests/ai/bridge/keyboard-event.test.ts
  packages/web-integration/tests/ai/bridge/temp.test.ts
  packages/web-integration/tests/ai/web/puppeteer/keyboard-event.test.ts
  pnpm-lock.yaml
Labels: change: feat

#335 fix: resolve shared exports error
  packages/shared/package.json
  packages/web-integration/vitest.config.ts
Labels: change: fix

#343 fix(prompt): resolve params format error
  packages/midscene/src/ai-model/prompt/llm-planning.ts
  packages/midscene/tests/ai/evaluate/plan/planning.test.ts
Labels: change: fix
