Repository web-infra-dev/midscene, pull requests merged in 2025-03, with the labels that each got.

#440 fix: race condition in bridge mode
  packages/cli/src/yaml-runner.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/evaluation/page-cases/planning/aweme-login-vl.json
  packages/evaluation/page-cases/planning/todo-vl.json
  packages/evaluation/src/test-analyzer.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/task-cache.ts
Labels: change: fix

#445 fix(esm): resolve cli can't load esm module
  packages/cli/bin/midscene
  packages/cli/modern.config.ts
  packages/cli/package.json
  packages/cli/src/cli-utils.ts
  packages/core/modern.config.ts
  packages/core/package.json
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/prompt/util.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/index.ts
  packages/core/src/utils.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  packages/shared/src/extractor/constants.ts
  packages/shared/src/extractor/index.ts
  packages/shared/src/extractor/web-extractor.ts
  packages/shared/src/node/fs.ts
  packages/visualizer/modern.config.ts
  packages/visualizer/package.json
  packages/visualizer/scripts/build-html.ts
  packages/visualizer/scripts/building-utils.ts
  packages/web-integration/bin/midscene-playground
  packages/web-integration/modern.config.ts
  packages/web-integration/package.json
  packages/web-integration/scripts/check-exports.js
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/playground/server.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  pnpm-lock.yaml
Labels: change: fix

#446 fix: enhance CoT of qwen
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/web-integration/src/chrome-extension/page.ts
Labels: change: fix

#448 fix: planning prompt
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/evaluation/page-cases/planning/antd-form-vl.json
  packages/evaluation/page-cases/planning/antd-form-vl.json-planning-coordinates-annotated.png
  packages/evaluation/page-cases/planning/antd-tooltip-vl.json
  packages/evaluation/page-cases/planning/antd-tooltip-vl.json-planning-coordinates-annotated.png
  packages/evaluation/page-cases/planning/aweme-login-vl.json
  packages/evaluation/src/test-analyzer.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/shared/package.json
  packages/shared/src/utils.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/tests/playwright.config.ts
  pnpm-lock.yaml
Labels: change: fix

#452 feat(core): fix MIDSCENE_CACHE=true not work
  packages/core/src/env.ts
Labels: change: feat

#453 fix: add an field for CoT in qwen
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/evaluation/page-cases/planning/todo-vl.json
  packages/evaluation/page-cases/planning/todo-vl.json-planning-coordinates-annotated.png
  packages/evaluation/tests/llm-planning.test.ts
  packages/visualizer/src/component/detail-panel.tsx
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#460 fix: ai test
  apps/site/docs/en/faq.md
  apps/site/docs/zh/faq.md
  packages/core/package.json
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/tests/ai/extract/__snapshots__/extract.test.ts.snap
  packages/core/tests/ai/extract/extract.test.ts
  packages/core/tests/ai/llm-planning/__snapshots__/input.test.ts.snap
  packages/core/tests/ai/llm-planning/basic.test.ts
  packages/core/tests/ai/llm-planning/input.test.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/evaluation/tests/assertion.test.ts
  packages/evaluation/tests/util.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/tests/ai/web/playwright-report-test/todo-report.spec.ts
  packages/web-integration/tests/ai/web/playwright/util.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/playwright.config.ts
  packages/web-integration/vitest.config.ts
Labels: change: fix

#468 fix(web-integration): resolve waitForNavigation timeout
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#466 fix: prompt of vl
  apps/site/docs/en/API.mdx
  apps/site/docs/zh/API.mdx
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-locator.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-section-locator.ts
  packages/core/src/ai-model/prompt/util.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/env.ts
  packages/core/src/index.ts
  packages/core/src/insight/index.ts
  packages/core/src/insight/utils.ts
  packages/core/src/types.ts
  packages/core/tests/ai/llm-inspect.test.ts
  packages/core/tests/ai/llm-planning/basic.test.ts
  packages/core/tests/ai/llm-section-locator.test.ts
  packages/core/tests/unit-test/llm-planning.test.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/core/tests/unit-test/prompt/utils.test.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/core/tests/utils.ts
  packages/evaluation/package.json
  packages/evaluation/src/test-analyzer.ts
  packages/evaluation/tests/llm-locator.test.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/evaluation/tests/llm-section-locator.test.ts
  packages/evaluation/tests/util.ts
  packages/shared/src/extractor/util.ts
  packages/shared/src/extractor/web-extractor.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/unit-test/task-cache.test.ts
  packages/web-integration/tests/unit-test/web-extractor.test.ts
Labels: change: fix

#472 fix: cache matching
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/insight/index.ts
  packages/core/src/types.ts
  packages/shared/src/node/fs.ts
  packages/visualizer/src/component/sidebar.tsx
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/plan-builder.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/unit-test/__snapshots__/plan-builder.test.ts.snap
  packages/web-integration/tests/unit-test/plan-builder.test.ts
Labels: change: fix

#482 feat: export overrideAIConfig in chrome extension
  packages/web-integration/src/chrome-extension/index.ts
Labels: change: feat

#484 fix: #473
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/insight/index.ts
  packages/core/src/utils.ts
  packages/core/tests/ai/llm-section-locator.test.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/evaluation/src/test-analyzer.ts
  packages/shared/src/img/index.ts
  packages/shared/src/img/transform.ts
  packages/shared/tests/unit-test/image/__snapshots__/index.test.ts.snap
  packages/shared/tests/unit-test/image/index.test.ts
  packages/web-integration/src/common/task-cache.ts
Labels: change: fix

#489 feat(playwright): add aiTap/aiInput and other AI actions for Playwright integration
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/tests/ai/web/playwright/ai-shop.spec.ts
  packages/web-integration/tests/ai/web/playwright/fixture.ts
Labels: change: feat

#491 feat: update prompt for qwen
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/evaluation/page-cases/planning/antd-form-vl.json
  packages/evaluation/page-cases/planning/antd-form-vl.json-planning-coordinates-annotated.png
  packages/evaluation/page-cases/planning/antd-tooltip-vl.json
  packages/evaluation/page-cases/planning/antd-tooltip-vl.json-planning-coordinates-annotated.png
  packages/evaluation/page-cases/planning/todo-vl.json
  packages/evaluation/page-cases/planning/todo-vl.json-planning-coordinates-annotated.png
  packages/evaluation/tests/llm-planning.test.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#494 fix: ai test
  .github/workflows/ai-evaluation-qwen.yml
  packages/core/src/yaml.ts
  packages/core/tests/ai/insight/insight.test.ts
  packages/evaluation/tests/llm-planning.test.ts
Labels: change: fix

#499 docs: docs for instant actions
  apps/site/docs/en/API.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
Labels: change: docs

#497 fix: playwright integration
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/web/playwright/ai-auto-todo.spec.ts
Labels: change: fix

#501 docs: updat faq
  apps/site/docs/en/faq.md
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/prompting-tips.md
Labels: change: docs

#503 docs: lazy loading report.gif
  apps/site/docs/en/index.mdx
  apps/site/docs/zh/index.mdx
Labels: change: docs
