Repository web-infra-dev/midscene, pull requests merged in 2025-04, with the labels that each got.

#512 feat: use aiTap(prompt, opt) style interface
  apps/site/docs/en/API.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/public/flow.png
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/faq.md
  packages/cli/tests/__snapshots__/cli-utils.test.ts.snap
  packages/cli/tests/bin.test.ts
  packages/cli/tests/midscene_scripts/online/bing.yaml
  packages/cli/tests/midscene_scripts/online/todomvc.yaml
  packages/core/src/ai-model/inspect.ts
  packages/core/src/env.ts
  packages/core/src/insight/index.ts
  packages/core/src/types.ts
  packages/core/src/yaml.ts
  packages/core/tests/ai/insight/insight.test.ts
  packages/core/tests/unit-test/executor/index.test.ts
  packages/visualizer/src/component/sidebar.tsx
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/plan-builder.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/unit-test/__snapshots__/plan-builder.test.ts.snap
Labels: change: feat

#516 fix(report): resolve report script error
  apps/report/template/index.html
  packages/core/package.json
  packages/core/src/utils.ts
  packages/core/tests/unit-test/utils.test.ts
Labels: change: fix

#518 fix: force screenshot when the app doesn't allow it
  packages/android/src/index.ts
  packages/android/src/page/index.ts
  packages/android/tests/ai/utils.ts
  packages/web-integration/src/common/agent.ts
Labels: change: fix

#515 feat: print stats in debug
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/model-provider.md
  packages/android/src/page/index.ts
  packages/core/src/ai-model/service-caller/index.ts
Labels: change: feat

#517 feat: update deepThink interface
  apps/report/src/components/sidebar.tsx
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/prompt/llm-section-locator.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/insight/index.ts
  packages/core/src/insight/utils.ts
  packages/core/src/types.ts
  packages/core/src/yaml.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/evaluation/page-cases/section-locator/antd-tooltip.json
  packages/evaluation/page-cases/section-locator/antd-tooltip.json-coordinates-annotated.png
  packages/evaluation/tests/llm-section-locator.test.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: feat

#528 feat(llm): allow setting context for aiAction
  apps/site/docs/en/API.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/yaml.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/evaluation/page-cases/planning/todo-vl.json
  packages/evaluation/page-cases/planning/todo-vl.json-planning-coordinates-annotated.png
  packages/evaluation/tests/llm-planning.test.ts
  packages/evaluation/tests/util.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: feat

#529 fix: ci testing
  packages/core/tests/ai/llm-section-locator.test.ts
  packages/evaluation/src/test-analyzer.ts
  packages/web-integration/tests/ai/web/playwright-report-test/todo-report.spec.ts
Labels: change: fix

#527 docs: blog for instant action and deep think
  .gitignore
  CONTRIBUTING.md
  apps/site/docs/en/blog-introducing-instant-actions-and-deep-think.md
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/public/blog/coze-sidebar.png
  apps/site/docs/public/blog/report-coze-deep-think.png
  apps/site/docs/public/blog/report-instant-action.png
  apps/site/docs/public/blog/report-planning.png
  apps/site/docs/zh/blog-introducing-instant-actions-and-deep-think.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/rspress.config.ts
  packages/android/src/page/index.ts
Labels: change: docs

#530 docs: update blog
  apps/site/docs/en/blog-introducing-instant-actions-and-deep-think.md
  apps/site/docs/zh/blog-introducing-instant-actions-and-deep-think.md
Labels: change: docs

#534 fix: log filename
  packages/shared/src/logger.ts
Labels: change: fix

#537 fix(playwright): make test.describe work correctly with ai fixtures
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/tests/ai/web/playwright/ai-auto-todo.spec.ts
Labels: change: fix

#535 fix click event should move the mouse to the click area first
  packages/web-integration/src/chrome-extension/page.ts
Labels: change: fix

#541 fix(playwright): Prevent the test from ending due to consistent timeout of screenshots
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#545 fix: coords offset in vl locator
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/prompt/llm-locator.ts
  packages/core/src/ai-model/prompt/llm-section-locator.ts
  packages/core/src/index.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/evaluation/page-cases/inspect/aweme-login.json
  packages/evaluation/page-cases/inspect/taobao.json
  packages/evaluation/tests/llm-locator.test.ts
  packages/evaluation/tests/util.ts
Labels: change: fix

#547 fix(android): verify vl-model mode in AndroidAgent constructor
  packages/android/src/agent/index.ts
Labels: change: fix

#546 docs: add docs for android
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/integrate-with-android.mdx
Labels: change: docs

#553 feat(yaml): allow insecure https in yaml
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  packages/core/src/yaml.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: feat

#554 fix: rethrow error with android faq when adb error occured
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/public/android-usb-debug-en.png
  apps/site/docs/public/android-usb-debug.png
  apps/site/docs/zh/integrate-with-android.mdx
  packages/android/src/page/index.ts
  packages/android/src/utils/index.ts
Labels: change: fix

#551 feat: android yaml support
  .gitignore
  packages/cli/package.json
  packages/cli/src/yaml-runner.ts
  packages/cli/tests/midscene_scripts/online/todomvc.yaml
  packages/core/src/yaml.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/src/yaml/builder.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/src/yaml/utils.ts
  packages/web-integration/tests/unit-test/yaml/player.test.ts
  pnpm-lock.yaml
Labels: change: feat

#556 feat: disable http warning in yaml mode
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: feat

#559 docs: update caching docs
  apps/site/docs/en/caching.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/zh/caching.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/prompting-tips.md
  packages/evaluation/page-cases/inspect/online_order_list.json
  packages/evaluation/page-cases/inspect/online_order_list.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/taobao.json
  packages/evaluation/page-cases/inspect/taobao.json-coordinates-annotated.png
Labels: change: docs

#563 docs: add android playground docs
  README.zh.md
  apps/site/docs/en/API.mdx
  apps/site/docs/en/common/start-experience.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/quick-experience-with-android.mdx
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/public/android-playground.png
  apps/site/docs/public/android-set-env.png
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/common/start-experience.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/quick-experience-with-android.mdx
  apps/site/docs/zh/quick-experience.mdx
  apps/site/rspress.config.ts
  packages/core/CONTRIBUTING.md
Labels: change: docs

#566 fix: dry run
  packages/visualizer/src/component/playground/ServiceModeControl.tsx
Labels: change: fix

#565 feat: add uitars as vl mode
  packages/core/src/env.ts
  packages/core/src/insight/utils.ts
  packages/web-integration/src/common/agent.ts
Labels: change: feat

#569 fix(puppeteer): optimize puppeteer export
  packages/cli/src/yaml-runner.ts
  packages/web-integration/modern.config.ts
  packages/web-integration/package.json
  packages/web-integration/src/puppeteer/index.ts
Labels: change: fix

#564 feat(core): show warning for oversized image
  packages/core/src/ai-model/common.ts
Labels: change: feat

#575 fix(report): use tmpdir as fallback for log file
  packages/shared/src/common.ts
Labels: change: fix

#577 fix(report): do not call mkdir in browser
  packages/core/src/index.ts
  packages/core/src/insight/utils.ts
  packages/core/src/utils.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  packages/shared/src/common.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/yaml/player.ts
Labels: change: fix

#555 feat(yaml): allow running javascript in yaml
  .gitignore
  apps/site/docs/en/API.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  packages/cli/tests/__snapshots__/bin.test.ts.snap
  packages/cli/tests/bin.test.ts
  packages/cli/tests/midscene_scripts_bridge/new_tab/bing.yaml
  packages/core/src/yaml.ts
  packages/shared/src/common.ts
  packages/web-integration/.gitignore
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/yaml/player.ts
Labels: change: feat

#583 fix: esm for @yume-chan/async
  package.json
  patches/@yume-chan__async.patch
  pnpm-lock.yaml
Labels: change: fix

#584 feat: support tap in prompt
  apps/android-playground/src/App.tsx
  apps/chrome-extension/src/component/playground.tsx
  apps/report/src/components/playground.tsx
  packages/visualizer/src/component/env-config.tsx
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/playground/ConfigSelector.tsx
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/playground-constants.tsx
  packages/visualizer/src/component/playground/playground-types.ts
  packages/visualizer/src/component/playground/playground-utils.ts
  packages/visualizer/src/component/store/history.ts
  packages/visualizer/src/component/store/store.tsx
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/playground/server.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/ai/web/playwright/ai-shop.spec.ts
Labels: change: feat

#562 feat(mcp): provide midscene mcp server
  biome.json
  package.json
  packages/android-playground/.gitignore
  packages/core/src/env.ts
  packages/mcp/README.md
  packages/mcp/package.json
  packages/mcp/rslib.config.ts
  packages/mcp/scripts/inspect.mjs
  packages/mcp/src/index.ts
  packages/mcp/src/midscene.ts
  packages/mcp/src/resources.ts
  packages/mcp/src/tools.ts
  packages/mcp/src/utils.ts
  packages/mcp/tests/index.test.ts
  packages/mcp/tests/test-login.mjs
  packages/mcp/tests/tsconfig.json
  packages/mcp/tsconfig.json
  packages/mcp/vitest.config.ts
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  packages/web-integration/src/common/utils.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: change: feat

#586 fix: style of chrome
  apps/android-playground/src/App.less
  apps/chrome-extension/src/App.less
  apps/chrome-extension/src/extension/popup.less
  packages/android/src/page/index.ts
  packages/visualizer/src/component/playground/index.less
Labels: change: fix

#589 fix(visualizer): update type references and improve tooltip handling in components
  apps/android-playground/src/App.tsx
  apps/report/src/components/playground.tsx
  packages/visualizer/src/component/env-config.tsx
  packages/visualizer/src/component/playground/ServiceModeControl.tsx
  packages/visualizer/src/component/playground/index.less
  packages/web-integration/src/playground/server.ts
Labels: change: fix

#590 fix(core): race condition when initing env config
  packages/android/src/page/index.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/env.ts
Labels: change: fix

#593 fix(yaml): handle null case for android configuration in parseYamlScript function
  packages/cli/src/yaml-runner.ts
  packages/web-integration/src/yaml/utils.ts
Labels: change: fix

#594 fix(report): ai tap in report
  apps/android-playground/package.json
  apps/android-playground/src/App.tsx
  apps/report/src/components/playground.tsx
  commitlint.config.js
  packages/visualizer/src/component/playground/ServiceModeControl.tsx
  packages/visualizer/src/component/playground/playground-utils.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  pnpm-lock.yaml
Labels: change: fix

#595 fix(core): player title max width
  apps/chrome-extension/src/extension/bridge.less
  apps/chrome-extension/src/extension/popup.less
  packages/visualizer/src/component/player.less
  packages/visualizer/src/component/player.tsx
Labels: change: fix

#599 fix(mcp): resolve mcp server log error
  commitlint.config.js
  packages/mcp/.gitignore
  packages/mcp/package.json
  packages/mcp/src/index.ts
  packages/mcp/src/tools.ts
  packages/shared/src/utils.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  packages/web-integration/src/common/utils.ts
  pnpm-lock.yaml
Labels: change: fix

#601 docs(llm): update ui-tars 1.5 link
  README.md
  README.zh.md
Labels: change: docs

#598 fix(cli): keep window after cli running
  commitlint.config.js
  packages/cli/src/index.ts
Labels: change: fix

#597 fix(core): keep context in log file when locate fails
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/insight/index.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: fix

#596 fix(android): update styles and transitions in playground components
  apps/android-playground/src/App.less
  packages/visualizer/src/component/player.less
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/index.less
Labels: change: fix

#574 docs: update docs
  .vscode/settings.json
  README.md
  README.zh.md
  apps/site/docs/en/blog-support-android-automation.md
  apps/site/docs/zh/blog-support-android-automation.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/rspress.config.ts
  packages/core/src/ai-model/service-caller/index.ts
Labels: change: docs

#607 docs(android): automation demos
  CONTRIBUTING.md
  README.md
  README.zh.md
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/blog-support-android-automation.md
  apps/site/docs/en/blog-support-android-automation.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/common/prepare-android.mdx
  apps/site/docs/en/common/prepare-key-for-further-use.mdx
  apps/site/docs/en/common/setup-env.mdx
  apps/site/docs/en/common/start-experience.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/index.mdx
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/en/quick-experience-with-android.mdx
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/public/android-playground.png
  apps/site/docs/public/android-set-env.png
  apps/site/docs/public/blog/android-playground-lark-poster-cn.png
  apps/site/docs/public/blog/android-playground-lark-poster-en.png
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/blog-introducing-instant-actions-and-deep-think.md
  apps/site/docs/zh/blog-support-android-automation.md
  apps/site/docs/zh/blog-support-android-automation.mdx
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/common/prepare-android.mdx
  apps/site/docs/zh/common/prepare-key-for-further-use.mdx
  apps/site/docs/zh/common/setup-env.mdx
  apps/site/docs/zh/common/start-experience.mdx
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/model-provider.md
  apps/site/docs/zh/prompting-tips.md
  apps/site/docs/zh/quick-experience-with-android.mdx
  apps/site/docs/zh/quick-experience.mdx
  apps/site/rspress.config.ts
  commitlint.config.js
  packages/.vscode/settings.json
  packages/cli/tests/midscene_scripts/online/todomvc.yaml
  packages/core/src/insight/index.ts
Labels: change: docs

#613 docs(core): update model config doc
  .vscode/settings.json
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/model-provider.md
Labels: change: docs

#605 feat(core): adapt for gemini-2.5-pro
  .vscode/settings.json
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/zh/choose-a-model.md
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/common.ts
  packages/core/src/ai-model/prompt/llm-locator.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-section-locator.ts
  packages/core/src/env.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/core/tests/unit-test/utils.test.ts
Labels: change: feat

#615 feat(android): hide keyboard after type
  .husky/commit-msg
  packages/android/src/page/index.ts
Labels: change: feat

#614 style(chrome-extension): opt chrome logo icon
  apps/chrome-extension/src/App.less
  apps/chrome-extension/src/extension/popup.tsx
  apps/site/docs/zh/blog-support-android-automation.mdx
  packages/visualizer/src/component/github-star.less
  packages/visualizer/src/component/github-star.tsx
  packages/visualizer/src/component/logo.less
  packages/visualizer/src/component/logo.tsx
  packages/visualizer/src/index.tsx
Labels: change: feat

#609 feat(mcp): add puppeteer mode
  README.md
  README.zh.md
  packages/core/src/env.ts
  packages/mcp/package.json
  packages/mcp/src/index.ts
  packages/mcp/src/midscene.ts
  packages/mcp/src/puppeteer.ts
  packages/mcp/src/tools.ts
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/common.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/puppeteer/index.ts
  pnpm-lock.yaml
Labels: change: feat

#617 fix(mcp): optimize mcp navigate to new page
  packages/mcp/src/midscene.ts
  packages/mcp/src/puppeteer.ts
Labels: change: fix

#567 feat: support android device button
  packages/android/src/page/index.ts
  packages/android/tests/ai/travel.test.ts
  packages/core/package.json
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/types.ts
  packages/core/tests/unit-test/env.test.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/index.less
  packages/web-integration/src/common/page.d.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#625 feat(mcp): add report to response
  packages/mcp/src/midscene.ts
  packages/web-integration/src/common/agent.ts
Labels: change: feat

#621 feat(core): adapt gpt 4.1
  packages/core/src/ai-model/service-caller/index.ts
Labels: change: feat

#624 feat(web-integration): enhance timeout configurations and logging for network idle and navigation
  apps/site/docs/en/API.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/integrate-with-playwright.mdx
  packages/core/src/yaml.ts
  packages/shared/src/constants/index.ts
  packages/web-integration/package.json
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/puppeteer/page.ts
  packages/web-integration/tests/ai/web/playwright/fixture.ts
Labels: change: feat

#630 feat(mcp): add playwright-example and midscene api prompts
  packages/mcp/rslib.config.ts
  packages/mcp/src/index.ts
  packages/mcp/src/midscene.ts
  packages/mcp/src/playwright-example.txt
  packages/mcp/src/prompts.ts
Labels: change: feat

#626 fix(report): reduce context size in report file
  apps/report/rsbuild.config.ts
  apps/report/src/components/detail-panel.tsx
  apps/report/test-data/swag-lab.json
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/insight/index.ts
  packages/core/src/types.ts
  packages/core/src/utils.ts
  packages/shared/src/img/box-select.ts
  packages/visualizer/src/component/blackboard.tsx
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/replay-scripts.tsx
  packages/web-integration/src/common/utils.ts
Labels: change: fix

#629 feat(playwright): enhance report filename generation with unique identifiers and support split mode
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/reporter/index.ts
Labels: change: feat

#640 fix(visualizer): scroll for result container
  packages/visualizer/src/component/player.less
  packages/visualizer/src/component/playground/index.less
  packages/visualizer/src/component/replay-scripts.tsx
Labels: change: fix

#641 fix(visualizer): the style of error state in report
  apps/report/src/components/detail-panel.tsx
  apps/report/src/components/timeline.tsx
  apps/report/test-data/error.json
  packages/visualizer/src/component/player.tsx
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#643 fix(web-integration): sanitize cacheId to replace illegal path characters
  packages/web-integration/src/common/task-cache.ts
Labels: change: fix

#644 fix(puppeter): check close status before close popup
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/puppeteer/index.ts
Labels: change: fix

#648 feat(mcp): optimize mcp tools args and add resource mimeType
  apps/chrome-extension/src/extension/bridge.tsx
  packages/mcp/src/index.ts
  packages/mcp/src/midscene.ts
Labels: change: feat

#645 fix(android): add mouse click and keyboard press for input handling
  packages/android/src/page/index.ts
Labels: change: fix

#652 docs(mcp): optimize playwright example
  packages/mcp/src/playwright-example.txt
Labels: change: docs

#656 docs(mcp): add mcp doc
  apps/site/docs/en/mcp.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/mcp.mdx
  apps/site/rspress.config.ts
Labels: change: docs

#616 feat(llm): adapt UI tars 1.5
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/model-provider.md
  package.json
  packages/core/package.json
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/insight/utils.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/shared/package.json
  packages/shared/src/env.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  pnpm-lock.yaml
Labels: change: feat

#660 feat(mcp): add playwright example tool to help generate playwright test code
  packages/mcp/package.json
  packages/mcp/src/index.ts
  packages/mcp/src/midscene.ts
Labels: change: feat

#661 docs(core): update docs for doubao vl model
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/mcp.mdx
  apps/site/docs/en/model-provider.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/mcp.mdx
  apps/site/docs/zh/model-provider.md
Labels: change: docs

#662 docs(mcp): optimize mcp showcase and add how to get report
  apps/site/docs/en/mcp.mdx
  apps/site/docs/zh/mcp.mdx
  packages/mcp/README.md
  packages/mcp/src/index.ts
Labels: change: docs

#668 feat(bridge): enhance agent and server listening functionality
  packages/mcp/src/midscene.ts
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/io-server.ts
Labels: change: feat

#667 fix(mcp): resolve MCP Bridge server connection timeout, then shut down MCP server
  packages/mcp/src/midscene.ts
  packages/web-integration/src/bridge-mode/io-server.ts
Labels: change: fix

#670 fix(mcp): resolve mcp bridge server connect timeout
  packages/mcp/src/midscene.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  pnpm-lock.yaml
Labels: change: fix

#671 feat(mcp): make mcp navigated faster
  packages/mcp/package.json
  packages/mcp/src/midscene.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  pnpm-lock.yaml
Labels: change: feat

#658 feat(web-integration): add support for new agent method(aiBoolean, aiString, aiNumber, aiLocate)
  apps/report/src/components/detail-side.tsx
  apps/report/src/components/sidebar.tsx
  apps/site/docs/en/API.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/integrate-with-playwright.mdx
  package.json
  packages/core/src/ai-model/action-executor.ts
  packages/core/src/ai-model/prompt/extraction.ts
  packages/core/src/ai-model/prompt/ui-tars-locator.ts
  packages/core/src/ai-model/prompt/ui-tars-planning.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/types.ts
  packages/core/tests/unit-test/env.test.ts
  packages/core/tests/unit-test/mocks/intl-mock.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/core/tests/unit-test/prompt/ui-tars-planning.test.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/mcp/src/playwright-example.txt
  packages/shared/package.json
  packages/shared/tests/unit-test/fs.test.ts
  packages/shared/tests/unit-test/image/__snapshots__/index.test.ts.snap
  packages/shared/tests/unit-test/image/index.test.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/plan-builder.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/tests/unit-test/__snapshots__/client-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/client-extractor.test.ts
  packages/web-integration/tests/unit-test/yaml/__snapshots__/utils.test.ts.snap
  packages/web-integration/tests/unit-test/yaml/player.test.ts
Labels: change: feat

#672 feat(mcp): make mcp navigated faster
  packages/mcp/package.json
  packages/mcp/src/midscene.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  pnpm-lock.yaml
Labels: change: feat

#677 docs(core): update profiling config
  apps/site/docs/en/API.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/choose-a-model.md
Labels: change: docs

#673 docs(core): update docs for aiQuery
  apps/site/docs/en/API.mdx
  apps/site/docs/zh/API.mdx
Labels: change: docs

#676 fix(mcp): mcp error connection
  .vscode/settings.json
  package.json
  packages/mcp/package.json
  packages/mcp/src/index.ts
  packages/mcp/src/midscene.ts
  packages/mcp/src/tools.ts
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/common.ts
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/bridge-mode/io-server.ts
  packages/web-integration/tests/unit-test/bridge/io.test.ts
  pnpm-lock.yaml
Labels: change: fix

#679 fix(core): id conflict in quick answer
  apps/report/src/components/detail-side.tsx
  apps/site/docs/zh/choose-a-model.md
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/util.ts
  packages/core/tests/unit-test/llm-planning.test.ts
Labels: change: fix

#684 feat(android): customize adb path
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  packages/android/src/page/index.ts
  packages/shared/src/env.ts
Labels: change: feat
