Repository web-infra-dev/midscene, pull requests merged in 2025-02, with the labels that each got.

#361 feat(cache): supports ui-tars model caching capability
  README.md
  README.zh.md
  apps/site/docs/en/caching.mdx
  apps/site/docs/public/cache/no-cache-time.png
  apps/site/docs/public/cache/use-cache-time.png
  apps/site/docs/zh/caching.mdx
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/ai/bridge/temp.test.ts
  packages/web-integration/tests/ai/web/playwright/ai-auto-todo.spec.ts
Labels: change: feat

#365 fix: improve waitForNetworkIdle with timeout handling
  packages/web-integration/src/playwright/ai-fixture.ts
Labels: change: fix

#370 fix(ui-tars): resolve page down and page up event error
  packages/shared/src/us-keyboard-layout.ts
  packages/shared/tests/unit-test/keyboard.test.ts
Labels: change: fix

#371 fix: ai evaluation
  .github/workflows/ai-evaluation.yml
  packages/evaluation/page-cases/assertion/online_order.json
Labels: change: fix

#374 fix: upgrade langsmith sdk
  apps/site/docs/en/API.md
  apps/site/docs/zh/API.md
  packages/midscene/package.json
  pnpm-lock.yaml
Labels: change: fix

#373 fix: correctly collect elements in absolute container
  packages/shared/src/extractor/util.ts
  packages/web-integration/tests/unit-test/__snapshots__/web-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/fixtures/web-extractor/index.html
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
Labels: change: fix

#379 fix: update discord links #375
  README.md
  README.zh.md
  apps/site/docs/en/index.mdx
  apps/site/docs/zh/index.mdx
  apps/site/rspress.config.ts
Labels: change: fix

#384 fix(keybord): resolve selectAll/Copy/Paste event
  packages/cli/package.json
  packages/web-integration/package.json
  packages/web-integration/src/appium/page.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/bridge/temp.test.ts
  packages/web-integration/tests/ai/web/playwright/ai-auto-todo.spec.ts
  packages/web-integration/tests/ai/web/puppeteer/agent.test.ts
  packages/web-integration/tests/unit-test/util.test.ts
  packages/web-integration/vitest.config.ts
  pnpm-lock.yaml
Labels: change: fix

#390 fix: typo of !389
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/component/store.tsx
Labels: change: fix

#389 feat(browser): Add the forceSameTabNavigation configuration to prevent AI from opening new pages during operations, thus avoiding task interruptions.
  apps/site/docs/en/API.md
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/zh/API.md
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  packages/cli/package.json
  packages/evaluation/package.json
  packages/midscene/package.json
  packages/midscene/src/yaml.d.ts
  packages/shared/package.json
  packages/visualizer/src/component/playground-component.tsx
  packages/visualizer/src/component/store.tsx
  packages/visualizer/src/extension/popup.tsx
  packages/web-integration/package.json
  packages/web-integration/src/bridge-mode/common.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/playwright/page.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/puppeteer/index.ts
  packages/web-integration/tests/ai/bridge/agent.test.ts
  packages/web-integration/tests/ai/bridge/keyboard-event.test.ts
  packages/web-integration/tests/ai/bridge/open-new-tab.test.ts
  packages/web-integration/tests/ai/bridge/temp.test.ts
  packages/web-integration/tests/ai/web/playwright/ai-online-order.spec.ts
  packages/web-integration/tests/ai/web/playwright/open-new-tab.spec.ts
  packages/web-integration/tests/ai/web/puppeteer/open-new-tab.test.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  packages/web-integration/vitest.config.ts
  pnpm-lock.yaml
Labels: change: feat

#391 fix(browser-event): optimize limit open new tab script and add yaml test
  packages/cli/package.json
  packages/cli/tests/bridge.test.ts
  packages/cli/tests/cli-utils.test.ts
  packages/cli/tests/midscene_scripts_bridge/new_tab/open-new-tab.yaml
  packages/cli/vitest.config.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/tests/ai/bridge/open-new-tab.test.ts
Labels: change: fix

#380 feat(reporting): Add test ID to test data attributes
  packages/web-integration/src/playwright/reporter/index.ts
Labels: change: feat

#392 fix(report): resolve the report generation failure caused by the absence of a selector
  packages/midscene/src/types.ts
  packages/visualizer/src/component/replay-scripts.tsx
  packages/web-integration/src/common/tasks.ts
Labels: change: fix

#396 fix(report): reduce playwright report size
  packages/web-integration/playwright.config.ts
  packages/web-integration/src/playwright/reporter/index.ts
Labels: change: fix

#401 fix: partial scroll issue in chrome extension
  packages/midscene/src/ai-model/common.ts
  packages/midscene/src/ai-model/service-caller/index.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#407 fix: coord bias of Qwen model
  packages/evaluation/page-cases/inspect/antd-carousel.json
  packages/evaluation/page-cases/inspect/antd-carousel.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/aweme-login.json
  packages/evaluation/page-cases/inspect/aweme-login.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/aweme-play.json
  packages/evaluation/page-cases/inspect/aweme-play.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/online_order.json
  packages/evaluation/page-cases/inspect/online_order.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/online_order_list.json
  packages/evaluation/page-cases/inspect/online_order_list.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/taobao.json
  packages/evaluation/page-cases/inspect/taobao.json-coordinates-annotated.png
  packages/evaluation/page-cases/inspect/todo.json
  packages/evaluation/page-cases/inspect/todo.json-coordinates-annotated.png
  packages/evaluation/tests/util.ts
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/llm-planning.ts
  packages/shared/src/img/box-select.ts
  packages/shared/src/img/index.ts
  packages/shared/src/img/info.ts
  packages/shared/src/img/transform.ts
  packages/shared/tests/unit-test/__snapshots__/tree.test.ts.snap
  packages/shared/tests/unit-test/image/__snapshots__/index.test.ts.snap
  packages/shared/tests/unit-test/image/index.test.ts
Labels: change: fix

#410 fix: ci of qwen model
  .github/workflows/ai-evaluation.yml
  README.md
  README.zh.md
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/quick-experience.mdx
  packages/evaluation/tests/llm-locator.test.ts
  packages/evaluation/tests/test-analyzer.ts
  packages/midscene/src/ai-model/prompt/llm-planning.ts
  packages/midscene/src/insight/utils.ts
  packages/midscene/tests/ai/llm-planning/__snapshots__/basic.test.ts.snap
  packages/midscene/tests/ai/llm-planning/basic.test.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/tests/ai/bridge/open-new-tab.test.ts
  packages/web-integration/tests/ai/web/playwright/open-new-tab.spec.ts
  packages/web-integration/tests/ai/web/puppeteer/agent.test.ts
  packages/web-integration/tests/ai/web/puppeteer/open-new-tab.test.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: fix

#417 docs: optimize bridge api structure
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
Labels: change: docs

#422 docs: update faq
  apps/site/docs/en/faq.md
  apps/site/docs/zh/faq.md
Labels: change: docs

#412 feat(core/ui-tars): support aiAssert() & aiWaitFor for UI-Tars model
  packages/midscene/src/ai-model/inspect.ts
  packages/midscene/src/ai-model/prompt/assertion.ts
  packages/midscene/src/ai-model/service-caller/index.ts
  packages/midscene/tests/ai/connectivity.test.ts
  packages/midscene/tests/ai/ui-tars-planning/output.png
  packages/midscene/tests/ai/ui-tars-planning/plan-to-target.test.ts
  packages/midscene/tests/unit-test/prompt/assertion.test.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#427 fix(core): the prompt of qwen
  apps/site/docs/en/API.mdx
  packages/evaluation/page-cases/planning/todo-vl.json
  packages/evaluation/tests/test-analyzer.ts
  packages/midscene/src/ai-model/llm-planning.ts
  packages/midscene/src/ai-model/prompt/llm-planning.ts
  packages/midscene/src/ai-model/service-caller/index.ts
  packages/midscene/src/env.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: fix

#428 docs: update instruction for bridge mode
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/public/bridge_in_extension.jpg
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: docs

#430 feat(yaml): Add cache support for yaml files, allowing file-level caching to improve execution speed and stability. Cache ID is automatically set to yaml filename.
  apps/site/docs/en/caching.mdx
  apps/site/docs/zh/caching.mdx
  packages/cli/src/yaml-runner.ts
  packages/web-integration/modern.config.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: feat

#429 fix: over planning for Qwen in page with form
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/prompting-tips.md
  apps/site/docs/zh/quick-experience.mdx
  packages/evaluation/data-generator/generator-headless.spec.ts
  packages/evaluation/page-cases/planning/antd-form-vl.json
  packages/evaluation/page-cases/planning/aweme-login-vl.json
  packages/evaluation/page-data/antd-form/element-snapshot.json
  packages/evaluation/page-data/antd-form/element-tree.json
  packages/evaluation/page-data/antd-form/element-tree.txt
  packages/evaluation/page-data/antd-form/input.png
  packages/evaluation/page-data/antd-form/output.png
  packages/evaluation/page-data/antd-form/output_without_text.png
  packages/evaluation/page-data/antd-form/resize-output.png
  packages/evaluation/tests/assertion.test.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/midscene/package.json
  packages/midscene/src/ai-model/llm-planning.ts
  packages/midscene/src/ai-model/prompt/assertion.ts
  packages/midscene/src/ai-model/prompt/llm-planning.ts
  packages/midscene/src/types.ts
  packages/midscene/tests/ai/llm-planning/basic.test.ts
  packages/midscene/tests/unit-test/prompt/__snapshots__/assertion.test.ts.snap
  packages/midscene/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/midscene/tests/unit-test/prompt/assertion.test.ts
  packages/visualizer/src/component/detail-side.tsx
  packages/web-integration/package.json
  packages/web-integration/src/common/tasks.ts
Labels: change: fix
