Repository web-infra-dev/midscene, pull requests merged in 2025-07, with the labels that each got.

#876 fix(android): change tap input to swipe for better interaction responsiveness
  packages/android/src/page/index.ts
Labels: change: fix

#880 feat(web-integration): override timeout from fixture
  apps/site/docs/en/API.mdx
  apps/site/docs/zh/API.mdx
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/index.ts
  packages/web-integration/src/playwright/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/puppeteer/index.ts
  packages/web-integration/src/puppeteer/page.ts
Labels: change: feat

#879 feat(agent): add onDumpUpdate callback and refactor afterTaskRunning to await its execution
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/playwright/ai-fixture.ts
Labels: change: feat

#887 fix(core): adjust read size and improve HTML end position calculation for UTF-8 compatibility
  packages/core/src/utils.ts
  packages/core/tests/unit-test/utils.test.ts
Labels: change: fix

#900 fix(web-integration): trigger onDumpUpdate in logScreenshot
  packages/web-integration/src/common/agent.ts
Labels: change: fix

#898 fix(puppeteer): page-level cookie API is deprecated. Use Browser.setC…
  packages/web-integration/src/puppeteer/agent-launcher.ts
Labels: change: fix

#912 feat(chrome-extension): use indexedDB in playground and extension
  apps/chrome-extension/src/components/playground.tsx
  apps/chrome-extension/src/extension/bridge.tsx
  apps/chrome-extension/src/scripts/worker.ts
  apps/chrome-extension/src/utils.ts
  apps/chrome-extension/src/utils/baseDB.ts
  apps/chrome-extension/src/utils/bridgeDB.ts
  apps/chrome-extension/src/utils/chrome.ts
  apps/chrome-extension/src/utils/playgroundDB.ts
  packages/visualizer/src/extension/utils.ts
Labels: change: feat

#913 feat(core): allow configuring max recycle limits
  .vscode/settings.json
  apps/site/docs/en/API.mdx
  apps/site/docs/en/model-provider.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/model-provider.mdx
  packages/cli/package.json
  packages/cli/src/cli-utils.ts
  packages/cli/src/index.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/shared/src/env.ts
  packages/web-integration/src/common/tasks.ts
  pnpm-lock.yaml
Labels: change: feat

#919 fix(web): refine debug log
  packages/web-integration/src/common/utils.ts
Labels: change: fix

#921 feat(android): distinguish the path of each screenshot
  packages/android/src/page/index.ts
  packages/core/tests/ai/llm-section-locator.test.ts
Labels: change: feat

#929 feat(recorder): add retry mechanism for describe calls to enhance reliability and optimize input label events
  apps/chrome-extension/src/utils/eventOptimizer.ts
  packages/recorder/src/recorder-iife-index.ts
  packages/recorder/src/recorder.ts
Labels: change: feat

#927 docs(site): 0.22 & 0.23 changelog
  .vscode/settings.json
  apps/site/docs/en/changelog.mdx
  apps/site/docs/zh/changelog.mdx
Labels: change: docs

#926 feat(web-integration): add cache filename length configuration and tests
  packages/shared/src/env.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/tests/unit-test/task-cache.test.ts
Labels: change: feat

#935 fix(web-integration): side effect
  packages/web-integration/src/common/task-cache.ts
Labels: change: fix

#934 style(report): update padding for page navigation and clean up task list styles
  apps/report/src/App.less
  apps/report/src/components/detail-side.less
  apps/report/src/components/detail-side.tsx
  apps/report/src/components/sidebar.less
Labels: change: feat

#936 fix(web-integration): add token usage for ui-tars planning
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: fix

#941 fix(core): generate xpath for svg
  packages/android/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/mcp/package.json
  packages/recorder/package.json
  packages/shared/package.json
  packages/shared/src/extractor/locator.ts
  packages/shared/src/extractor/web-extractor.ts
Labels: change: fix

#943 fix(web-intergration): fix typo
  packages/web-integration/src/yaml/player.ts
Labels: change: fix

#945 fix(report): replay twice in report
  apps/report/src/App.tsx
  apps/report/src/components/detail-side.less
  apps/report/src/components/detail-side.tsx
Labels: change: fix

#951 fix(report): can not switch report
  apps/report/src/App.tsx
  apps/report/src/components/detail-side.less
Labels: change: fix

#960 docs(mcp): update android mcp
  apps/site/docs/en/mcp-android.mdx
  apps/site/docs/zh/mcp-android.mdx
Labels: change: docs

#965 feat(web-integration): let plan before locate in cache file
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/tests/unit-test/task-cache.test.ts
Labels: change: feat

#963 feat(android): add long press functionality
  packages/android/src/page/index.ts
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/types.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/web-integration/src/common/page.d.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/tests/ai/web/puppeteer/order-case.test.ts
  packages/web-integration/tests/ai/web/puppeteer/svg-case.test.ts
Labels: change: feat

#970 fix(ci): todo-report.spec.ts
  packages/web-integration/tests/playwright.config.ts
Labels: change: fix

#967 feat(core): allow running in worker
  packages/core/src/ai-model/action-executor.ts
  packages/core/src/types.ts
  packages/core/src/utils.ts
  packages/shared/src/img/get-jimp.ts
  packages/shared/src/node/fs.ts
  packages/shared/src/utils.ts
  packages/visualizer/src/component/replay-scripts.tsx
  packages/web-integration/src/chrome-extension/dynamic-scripts.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playground/server.ts
  packages/web-integration/src/yaml/player.ts
Labels: change: feat
