Repository web-infra-dev/midscene, pull requests merged in 2025-08, with the labels that each got.

#980 fix(core): fix overrider
  packages/shared/src/env.ts
  packages/shared/tests/unit-test/env.test.ts
Labels: change: fix

#981 docs(site): 0.24 changelog
  apps/site/docs/en/changelog.mdx
  apps/site/docs/zh/changelog.mdx
Labels: change: docs

#985 docs(deps): upgrade Rspress to beta.24 and add LlmsCopyButton
  apps/site/docs/en/api.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/blog-programming-practice-using-structured-api.md
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/caching.mdx
  apps/site/docs/en/changelog.mdx
  apps/site/docs/en/common/start-experience.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/zh/api.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/blog-programming-practice-using-structured-api.md
  apps/site/docs/zh/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/zh/caching.mdx
  apps/site/docs/zh/changelog.mdx
  apps/site/docs/zh/common/start-experience.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-puppeteer.mdx
  apps/site/docs/zh/prompting-tips.md
  apps/site/package.json
  apps/site/rspress.config.ts
  apps/site/theme/index.tsx
  apps/site/tsconfig.json
  packages/mcp/rslib.config.ts
  packages/mcp/src/prompts.ts
  pnpm-lock.yaml
Labels: change: docs

#989 fix(core): add callAiFnWithStringResponse for string responses
  apps/chrome-extension/src/extension/recorder/utils.ts
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/service-caller/index.ts
Labels: change: fix

#990 fix(docs): correct code block formatting in integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
Labels: change: fix

#991 feat(recorder): add aiScroll function and enhance YAML task definitions
  packages/shared/src/constants/example-code.ts
Labels: change: feat

#996 fix(shared): use global config for env
  packages/shared/src/env.ts
Labels: change: fix

#1003 fix(report): manual log error message and stack when error stringify failed
  apps/report/src/components/detail-side.tsx
Labels: change: fix

#1005 fix(core): lazy parsing report content to improve performance
  apps/report/rsbuild.config.ts
  apps/report/src/App.tsx
  apps/report/src/components/PlaywrightCaseSelector.tsx
  apps/report/src/components/report-overview.tsx
  apps/report/src/components/sidebar.tsx
  apps/report/src/components/store.tsx
  apps/report/src/types.ts
Labels: change: fix

#984 docs(core): doc for prompting with images
  apps/site/docs/en/api.mdx
  apps/site/docs/zh/api.mdx
Labels: change: docs

#1010 fix(report): fix status icon logic for assert failed
  apps/report/rsbuild.config.ts
  apps/report/src/components/sidebar.tsx
Labels: change: fix

#1013 docs(core): freeze context
  apps/site/docs/en/api.mdx
  apps/site/docs/zh/api.mdx
Labels: change: docs

#1016 fix(web-intergration): add return for async type method
  packages/core/tests/ai/extract/extract.test.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#1023 fix(report): dropdown filter not work in report
  apps/chrome-extension/src/components/playground.less
  apps/report/rsbuild.config.ts
  apps/report/src/components/PlaywrightCaseSelector.less
  apps/report/src/components/PlaywrightCaseSelector.tsx
  packages/visualizer/src/component/playground/index.less
Labels: change: fix

#1025 fix(docs): fix mcp link
  .prettierignore
  README.md
  README.zh.md
  apps/site/docs/en/index.mdx
  apps/site/docs/zh/index.mdx
Labels: change: fix

#1024 feat(web-integration): add more method for playwright fixture
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  packages/web-integration/src/playwright/ai-fixture.ts
Labels: change: feat

#1030 fix(cli): automatically enable headed mode when keepWindow is true
  packages/cli/src/cli-utils.ts
  packages/cli/src/config-factory.ts
  packages/cli/tests/unit-test/config-factory.test.ts
Labels: change: fix

#1032 fix(report): handling for normal tasks in animation scripts like aiAssert/aiQuery
  packages/visualizer/src/component/replay-scripts.tsx
Labels: change: fix

#1031 feat(core): use action space to expose actions
  packages/android/src/page/index.ts
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/types.ts
  packages/core/tests/ai/llm-planning/basic.test.ts
  packages/core/tests/common.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/index.ts
  packages/web-integration/src/page.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/tests/ai/web/puppeteer/agent.test.ts
Labels: change: feat

#1037 feat(android): add hideKeyboardStrategy option to AndroidDevice and implement hideKeyboard method
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  packages/android/src/page/index.ts
  packages/android/tests/unit-test/page.test.ts
  packages/web-integration/src/common/page.d.ts
Labels: change: feat

#1038 fix(report): update assert failure condition in sidebar component to include task subtype
  apps/report/src/components/sidebar.tsx
  packages/web-integration/src/common/page.d.ts
Labels: change: fix

#1048 fix(web-integration): update overrideAIConfig to use extendMode for merging configurations
  packages/web-integration/src/playground/server.ts
  packages/web-integration/tests/ai/web/static/static-page.test.ts
Labels: change: fix

#1046 fix(core): testing for action space
  packages/core/tests/ai/llm-planning/input.test.ts
  packages/web-integration/src/playground/server.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
  packages/web-integration/tests/ai/web/static/static-page.test.ts
  packages/web-integration/tests/unit-test/task-cache.test.ts
Labels: change: fix

#1061 fix(web-integration): refactor version handling in task-cache and utils
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/tests/playwright.config.ts
Labels: change: fix

#1065 feat(report): add auto zoom toggle in Player component
  apps/report/package.json
  packages/visualizer/src/component/player.tsx
  packages/visualizer/src/component/playground/PlaygroundResult.tsx
  packages/visualizer/src/icons/global-perspective.svg
  packages/visualizer/src/icons/player-setting.svg
  pnpm-lock.yaml
Labels: change: feat

#1067 fix(android): enhance keyboard type handling to support parameter-specific autoDismissKeyboard option
  packages/android/src/page/index.ts
Labels: change: fix

#1070 fix(shared): ensure mime-type in base64 is correct
  apps/chrome-extension/src/extension/recorder/utils.ts
  packages/android/src/page/index.ts
  packages/android/tests/unit-test/page.test.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/image/index.ts
  packages/mcp/src/midscene.ts
  packages/mcp/src/resources.ts
  packages/shared/src/img/get-sharp.ts
  packages/shared/src/img/index.ts
  packages/shared/src/img/transform.ts
  packages/shared/tests/fixtures/2x2.png
  packages/shared/tests/unit-test/image/index.test.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#1085 fix aiWaitFor throw error unexceptly by adding doNotThrowError option
  apps/report/src/components/sidebar.tsx
  packages/core/src/insight/index.ts
  packages/core/src/yaml.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/unit-test/agent.test.ts
  packages/web-integration/tests/unit-test/page-task-executor-waitFor.test.ts
Labels: change: fix

#1002 feat(core): enable override modle config when create agent
  .vscode/settings.json
  apps/chrome-extension/src/extension/recorder/utils.ts
  apps/report/src/components/open-in-playground.tsx
  apps/report/src/components/sidebar.less
  apps/report/src/components/sidebar.tsx
  apps/report/test-data/multi-model.json
  packages/android/src/agent/index.ts
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/playwright-generator.ts
  packages/core/src/ai-model/prompt/util.ts
  packages/core/src/ai-model/prompt/yaml-generator.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/insight/index.ts
  packages/core/src/types.ts
  packages/core/src/utils.ts
  packages/core/tests/ai/insight/insight.test.ts
  packages/core/tests/unit-test/env.test.ts
  packages/core/tests/unit-test/executor/index.test.ts
  packages/core/tests/unit-test/llm-planning.test.ts
  packages/core/tests/unit-test/prompt/playwright-generator.test.ts
  packages/core/tests/unit-test/prompt/utils.test.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/evaluation/tests/util.ts
  packages/mcp/src/midscene.ts
  packages/shared/package.json
  packages/shared/src/env.ts
  packages/shared/src/env/constants.ts
  packages/shared/src/env/global-config.ts
  packages/shared/src/env/index.ts
  packages/shared/src/env/model-config.ts
  packages/shared/src/env/types.ts
  packages/shared/src/env/utils.ts
  packages/shared/tests/unit-test/env/decide-model.test.ts
  packages/shared/tests/unit-test/env/decide-sdk.test.ts
  packages/shared/tests/unit-test/env/env.test.ts
  packages/visualizer/src/component/describer.tsx
  packages/visualizer/src/index.tsx
  packages/web-integration/src/bridge-mode/index.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
  packages/web-integration/tests/unit-test/bridge/io.test.ts
  packages/web-integration/tests/unit-test/yaml/player.test.ts
Labels: change: feat, draft

#1097 fix(core): action player
  apps/chrome-extension/src/extension/recorder/components/RecordList.tsx
  apps/chrome-extension/src/extension/recorder/index.tsx
  apps/report/src/components/sidebar.tsx
  packages/cli/tests/ai/__snapshots__/bin.test.ts.snap
  packages/cli/tests/ai/bin.test.ts
  packages/core/src/insight/index.ts
  packages/core/tests/ai/extract/extract.test.ts
  packages/core/tests/ai/llm-inspect.test.ts
  packages/core/tests/ai/llm-planning/basic.test.ts
  packages/core/tests/ai/llm-section-locator.test.ts
  packages/core/tests/ai/streaming.test.ts
  packages/core/tests/evaluation.ts
  packages/shared/src/env/model-config.ts
  packages/shared/tests/unit-test/env/utils.test.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/ai/web/puppeteer/agent.test.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
  packages/web-integration/tests/unit-test/util.test.ts
  packages/web-integration/tests/unit-test/yaml/player.test.ts
Labels: change: fix

#1104 feat(report): display intent with model name
  apps/report/test-data/multi-model.json
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/types.ts
  packages/visualizer/src/component/replay-scripts.tsx
Labels: change: feat

#1105 fix(chore): playwright e2e case
  packages/web-integration/tests/ai/web/playwright/image-prompt.spec.ts
Labels: change: fix

#1107 docs(site): 0.27 changelog
  README.md
  README.zh.md
  apps/site/docs/en/changelog.mdx
  apps/site/docs/zh/changelog.mdx
Labels: change: docs

#1074 feat(chrome-extension): support all ai method for playground
  apps/chrome-extension/src/components/playground.tsx
  apps/chrome-extension/src/utils/playground-helpers.ts
  packages/visualizer/src/component/playground/FormField.tsx
  packages/visualizer/src/component/playground/HistorySelector.tsx
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/index.less
  packages/visualizer/src/component/playground/playground-constants.tsx
  packages/visualizer/src/component/playground/playground-types.ts
  packages/visualizer/src/component/playground/playground-utils.ts
  packages/visualizer/src/component/playground/types.ts
  packages/visualizer/src/component/replay-scripts.tsx
  packages/visualizer/src/component/store/history.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/playground/server.ts
Labels: change: feat

#1094 feat(android): support specific display id for android
  README.md
  README.zh.md
  apps/chrome-extension/static/manifest.json
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/mcp-android.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  apps/site/docs/zh/mcp-android.mdx
  packages/android/src/agent/index.ts
  packages/android/src/page/index.ts
  packages/android/tests/ai/multi-display.test.ts
  packages/android/tests/ai/setting.test.ts
  packages/android/tests/unit-test/page.test.ts
Labels: change: feat

#1125 fix(web-integration): midscene-playground bin entry
  packages/web-integration/bin/midscene-playground
  packages/web-integration/rslib.config.ts
Labels: change: fix

#1127 fix(web): bridge context error
  packages/core/src/agent/utils.ts
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
  packages/web-integration/src/bridge-mode/page-browser-side.ts
Labels: change: fix

#1128 fix(shared): fix maxTokens value is zero
  packages/core/src/ai-model/service-caller/index.ts
  packages/shared/src/env/types.ts
Labels: change: fix

#1131 fix(visualizer): adjust bottom padding in playground styles from 0.5px to 1px
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/index.less
Labels: change: fix

#1135 fix(core): evaluation code
  .gitignore
  apps/site/docs/en/choose-a-model.mdx
  apps/site/docs/zh/choose-a-model.mdx
  packages/evaluation/package.json
  packages/evaluation/src/test-analyzer.ts
  packages/evaluation/tests/llm-locator.test.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/evaluation/tsconfig.json
  packages/evaluation/vitest.config.ts
  packages/shared/src/env/global-config.ts
  packages/shared/src/env/model-config.ts
  packages/shared/src/env/utils.ts
  packages/shared/tests/unit-test/env/decide-model.test.ts
  packages/shared/tests/unit-test/env/decide-sdk.test.ts
  packages/shared/tests/unit-test/env/global-config.test.ts
  packages/web-integration/src/index.ts
Labels: change: fix

#1132 feat(android-playground, report): support all ai method in playground
  apps/android-playground/src/App.tsx
  apps/chrome-extension/src/components/playground.tsx
  apps/chrome-extension/src/utils/playground-helpers.ts
  apps/chrome-extension/static/manifest.json
  apps/report/src/components/playground.tsx
  packages/visualizer/src/component/playground/FormField.tsx
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/index.less
  packages/visualizer/src/component/playground/playground-execution.ts
  packages/visualizer/src/component/playground/playground-utils.ts
  packages/visualizer/src/component/playground/types.ts
  packages/visualizer/src/component/playground/useStaticPageAgent.ts
  packages/visualizer/src/index.tsx
  packages/web-integration/src/index.ts
  packages/web-integration/src/playground/common.ts
  packages/web-integration/src/playground/index.ts
  packages/web-integration/src/playground/server.ts
Labels: change: feat

#1138 feat(site): add performance configuration to disable build cache
  apps/site/rspress.config.ts
Labels: change: feat
