Repository web-infra-dev/midscene, pull requests merged in 2025-05, with the labels that each got.

#686 docs(site): update timeout parameters in API to include options for disabling timeouts
  apps/site/docs/en/API.mdx
  apps/site/docs/en/faq.md
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/faq.md
  apps/site/docs/zh/integrate-with-playwright.mdx
Labels: change: docs

#687 style(chrome-extension): update padding for popup layout with responsive design
  apps/chrome-extension/src/extension/popup.less
Labels: change: feat

#688 feat(android): fix custom adb path no effect
  packages/android/src/page/index.ts
Labels: change: feat

#692 docs(site): fix volcengine version USE_VLM_UI_TARS value and modify 火山云 to 火山引擎
  apps/site/docs/en/choose-a-model.md
  apps/site/docs/zh/choose-a-model.md
  apps/site/docs/zh/model-provider.md
Labels: change: docs

#693 feat(site): seo optimization
  apps/site/package.json
  apps/site/rspress.config.ts
  apps/site/theme/index.tsx
  packages/android/package.json
  packages/web-integration/package.json
  pnpm-lock.yaml
Labels: change: feat

#695 docs(mcp): add MCP to README
  README.md
  README.zh.md
Labels: change: docs

#694 docs(llm): add llm.txt
  apps/site/docs/en/llm-txt.mdx
  apps/site/docs/zh/llm-txt.mdx
  apps/site/package.json
  apps/site/rspress.config.ts
  apps/site/theme/index.tsx
  pnpm-lock.yaml
Labels: change: docs

#697 feat(site): update clarity script ID and Google site verification token
  apps/site/rspress.config.ts
Labels: change: feat

#649 feat(core): support HTTP proxy and reorder dependencies
  packages/core/package.json
  packages/core/src/ai-model/service-caller/index.ts
  packages/shared/src/env.ts
  pnpm-lock.yaml
Labels: change: feat

#699 fix(core): bundle template content into core package
  apps/chrome-extension/README.md
  apps/chrome-extension/package.json
  apps/chrome-extension/rsbuild.config.ts
  apps/chrome-extension/scripts/build-report-template.js
  apps/report/rsbuild.config.ts
  packages/core/package.json
  packages/core/src/utils.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/mcp/rslib.config.ts
Labels: change: fix

#710 fix(core): xpath logic
  packages/core/src/ai-model/prompt/util.ts
  packages/core/src/insight/index.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
Labels: change: fix

#714 fix(android): chinese input compatible with vivo android 14 system
  packages/android/bin/yadb
Labels: change: fix

#716 fix(core): update bbox preprocessing of ui-tars
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/tests/unit-test/utils.test.ts
Labels: change: fix

#709 docs(site): blog: Key to Automation Stability: Programming Practices Using Structured API
  apps/site/docs/en/blog-programming-practice-using-structured-api.md
  apps/site/docs/zh/blog-programming-practice-using-structured-api.md
  apps/site/rspress.config.ts
Labels: change: docs

#711 feat(web): use xpath and yaml as cache
  .vscode/settings.json
  apps/report/src/components/detail-side.tsx
  apps/site/docs/en/caching.mdx
  apps/site/docs/zh/caching.mdx
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/util.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/insight/index.ts
  packages/core/src/types.ts
  packages/core/tests/ai/llm-inspect.test.ts
  packages/core/tests/ai/ui-tars-planning/plan-to-target.test.ts
  packages/core/tests/unit-test/__snapshots__/llm-planning.test.ts.snap
  packages/core/tests/unit-test/executor/__snapshots__/index.test.ts.snap
  packages/core/tests/unit-test/executor/index.test.ts
  packages/core/tests/unit-test/llm-planning.test.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/shared/modern.config.ts
  packages/shared/package.json
  packages/shared/src/extractor/client-extractor.ts
  packages/shared/src/extractor/dom-util.ts
  packages/shared/src/extractor/index.ts
  packages/shared/src/extractor/locator.ts
  packages/shared/src/extractor/util.ts
  packages/shared/src/extractor/web-extractor.ts
  packages/shared/src/logger.ts
  packages/shared/src/node/fs.ts
  packages/shared/src/types/index.ts
  packages/web-integration/package.json
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/plan-builder.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/puppeteer/agent-launcher.ts
  packages/web-integration/src/web-element.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/ai/web/puppeteer/open-new-tab.test.ts
  packages/web-integration/tests/unit-test/__snapshots__/task-cache.test.ts.snap
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
  packages/web-integration/tests/unit-test/task-cache.test.ts
  packages/web-integration/tests/unit-test/yaml/__snapshots__/player.test.ts.snap
  packages/web-integration/tests/unit-test/yaml/__snapshots__/utils.test.ts.snap
  packages/web-integration/tests/unit-test/yaml/player.test.ts
  packages/web-integration/tests/unit-test/yaml/utils.test.ts
  pnpm-lock.yaml
Labels: change: feat

#726 fix(site): update playwright example docs.
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
Labels: change: fix

#728 docs: add deepwiki link
  README.md
  README.zh.md
Labels: change: docs

#719 docs(llm): add doubao-1.5-vl-pro model
  apps/site/docs/en/choose-a-model.mdx
  apps/site/docs/en/model-provider.mdx
  apps/site/docs/zh/choose-a-model.mdx
  apps/site/docs/zh/model-provider.mdx
Labels: change: docs

#732 fix cache bugs(scroll instant, text node info, cache hit condition)
  packages/shared/src/extractor/locator.ts
  packages/shared/src/extractor/util.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/unit-test/__snapshots__/web-extractor.test.ts.snap
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
  packages/web-integration/tests/unit-test/web-extractor.test.ts
Labels: change: fix

#736 fix(core): dump page context when locate fails
  packages/web-integration/src/common/tasks.ts
Labels: change: fix

#737 feat(evaluation): add screenspot v2 evaluation
  packages/evaluation/.gitignore
  packages/evaluation/README.md
  packages/evaluation/package.json
  packages/evaluation/tests/llm-section-locator.test.ts
  packages/evaluation/tests/screenspot-v2-evaluation.test.ts
  packages/evaluation/tests/util.ts
  packages/shared/src/img/box-select.ts
  pnpm-lock.yaml
Labels: change: feat

#740 feat(web-integration): support disable cache for a single api call
  apps/site/docs/en/API.mdx
  apps/site/docs/en/caching.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/caching.mdx
  package.json
  packages/core/src/yaml.ts
  packages/shared/src/extractor/util.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  pnpm-lock.yaml
Labels: change: feat

#746 docs(common): fix broken relative links
  apps/site/docs/en/common/prepare-android.mdx
  apps/site/docs/en/common/prepare-key-for-further-use.mdx
  apps/site/docs/en/common/setup-env.mdx
  apps/site/docs/en/common/start-experience.mdx
  apps/site/docs/zh/common/prepare-android.mdx
  apps/site/docs/zh/common/prepare-key-for-further-use.mdx
  apps/site/docs/zh/common/setup-env.mdx
  apps/site/docs/zh/common/start-experience.mdx
Labels: change: docs

#750 feat(core): add element describer
  apps/report/src/components/open-in-playground.tsx
  apps/report/test-data/taobao.json
  apps/site/docs/en/model-provider.mdx
  apps/site/docs/zh/model-provider.mdx
  packages/core/src/ai-model/common.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/prompt/assertion.ts
  packages/core/src/ai-model/prompt/describe.ts
  packages/core/src/ai-model/prompt/ui-tars-planning.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/insight/index.ts
  packages/core/src/types.ts
  packages/core/src/yaml.ts
  packages/core/tests/ai/insight/insight.test.ts
  packages/core/tests/unit-test/prompt/__snapshots__/describe.test.ts.snap
  packages/core/tests/unit-test/prompt/assertion.test.ts
  packages/core/tests/unit-test/prompt/describe.test.ts
  packages/core/tests/unit-test/prompt/ui-tars-planning.test.ts
  packages/shared/src/env.ts
  packages/shared/src/img/box-select.ts
  packages/visualizer/src/component/blackboard.tsx
  packages/visualizer/src/component/describer.less
  packages/visualizer/src/component/describer.tsx
  packages/visualizer/src/component/playground/index.less
  packages/visualizer/src/component/playground/playground-types.ts
  packages/visualizer/src/index.tsx
  packages/web-integration/src/bridge-mode/page-browser-side.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: feat

#745 fix(web-integration): sanitize content for reportHtmlContent
  apps/report/src/App.tsx
  apps/report/src/index.tsx
  packages/core/package.json
  packages/core/src/utils.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/shared/src/utils.ts
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
  pnpm-lock.yaml
Labels: change: fix

#749 fix(web-integration): 处理androi模式的yaml格式情况下，deviceId首位为0被去除的问题.
  packages/web-integration/src/yaml/utils.ts
Labels: change: fix

#759 fix(web-integration): chrome agent cache
  packages/android/src/page/index.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/page.d.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playground/static-page.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#766 fix(core): error in showing query result in playground
  apps/chrome-extension/src/component/playground.tsx
  apps/report/src/components/playground.tsx
Labels: change: fix

#757 fix(core): update error log of dump file
  .github/workflows/ai-evaluation-qwen.yml
  .github/workflows/ai-evaluation.yml
  .github/workflows/ai-unit-test.yml
  .github/workflows/ai.yml
  CONTRIBUTING.md
  package.json
  packages/core/CONTRIBUTING.md
  packages/core/src/ai-model/action-executor.ts
  packages/core/src/insight/utils.ts
  packages/core/src/utils.ts
  packages/core/tests/ai/llm-inspect.test.ts
  packages/core/tests/ai/llm-planning/input.test.ts
  packages/core/tests/unit-test/llm-planning.test.ts
  packages/evaluation/page-cases/inspect/online_order.json
  packages/evaluation/tests/llm-locator.test.ts
  packages/visualizer/src/component/replay-scripts.tsx
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/tests/ai/web/playwright-report-test/todo-report.spec.ts
Labels: change: fix

#772 fix(web-integration): Allow the timeout to be set to 0
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/puppeteer/page.ts
Labels: change: fix

#773 fix(core): fix planning test
  .github/workflows/ai.yml
  apps/report/src/App.tsx
  apps/report/src/components/detail-panel.tsx
  apps/report/src/components/store.tsx
  apps/report/src/index.tsx
  apps/report/test-data/query-only.json
  apps/site/docs/en/API.mdx
  apps/site/docs/zh/API.mdx
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/visualizer/src/component/blackboard.tsx
  packages/visualizer/src/component/replay-scripts.tsx
  packages/web-integration/tests/ai/web/puppeteer/showcase.test.ts
Labels: change: fix

#776 docs(core): update blog of workflow
  apps/site/docs/en/blog-programming-practice-using-structured-api.md
  apps/site/docs/zh/blog-programming-practice-using-structured-api.md
Labels: change: docs

#777 fix(web-integration): output opt is invalid in yaml
  package.json
  packages/.vscode/settings.json
  packages/cli/tests/__snapshots__/cli.test.ts.snap
  packages/cli/tests/__snapshots__/yaml.test.ts.snap
  packages/cli/tests/ai/__snapshots__/bin.test.ts.snap
  packages/cli/tests/ai/bin.test.ts
  packages/cli/tests/ai/bridge.test.ts
  packages/cli/tests/midscene_scripts/local/local-error-message.yml
  packages/cli/tests/midscene_scripts/online/online.yaml
  packages/cli/tests/midscene_scripts/online/todomvc.yaml
  packages/cli/tests/unit-test/__snapshots__/cli-utils.test.ts.snap
  packages/cli/tests/unit-test/cli-utils.test.ts
  packages/cli/vitest.config.ts
  packages/core/src/yaml.ts
  packages/core/vitest.config.ts
  packages/shared/package.json
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/unit-test/yaml/player.test.ts
  packages/web-integration/vitest.config.ts
Labels: change: fix

#786 fix(android): add screen orientation detection in getScreenSize method
  packages/android/src/page/index.ts
Labels: change: fix

#780 feat(core,web-integration): support right-click action (#762)
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/index.ts
  packages/core/src/types.ts
  packages/core/src/yaml.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/types-rightclick.test.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/plan-builder.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/ui-utils.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/unit-test/__snapshots__/plan-builder.test.ts.snap
  packages/web-integration/tests/unit-test/agent-rightclick.test.ts
  packages/web-integration/tests/unit-test/page-task-executor-rightclick.test.ts
  packages/web-integration/tests/unit-test/plan-builder.test.ts
  packages/web-integration/tests/unit-test/yaml/__snapshots__/utils.test.ts.snap
  packages/web-integration/tests/unit-test/yaml/player-rightclick.test.ts
  packages/web-integration/tests/unit-test/yaml/utils.test.ts
Labels: change: feat
