Repository web-infra-dev/midscene, pull requests merged in 2025-09, with the labels that each got.

#1148 fix(chrome-extension): allow multiple config overrides
  package.json
  packages/shared/src/env/global-config.ts
Labels: change: fix

#1152 feat(android): support planning cache for android
  apps/site/docs/en/blog-support-android-automation.mdx
  apps/site/docs/en/caching.mdx
  apps/site/docs/zh/blog-support-android-automation.mdx
  apps/site/docs/zh/caching.mdx
  packages/core/src/agent/agent.ts
  packages/core/src/agent/tasks.ts
Labels: change: feat

#1157 feat(android): enhance input clearing strategy based on IME settings
  packages/android/src/device.ts
Labels: change: feat

#1160 fix(core): device type definition
  packages/core/src/agent/agent.ts
  packages/core/src/device/index.ts
  packages/core/src/types.ts
  packages/web-integration/src/web-element.ts
Labels: change: fix

#1147 feat(playground): implement PlaygroundSDK for execution management
  apps/android-playground/package.json
  apps/android-playground/src/App.tsx
  apps/chrome-extension/package.json
  apps/chrome-extension/src/components/playground.tsx
  apps/chrome-extension/src/extension/bridge.tsx
  apps/chrome-extension/src/utils/bridgeConnector.ts
  apps/chrome-extension/src/utils/playground-helpers.ts
  apps/chrome-extension/tsconfig.json
  apps/report/package.json
  apps/report/src/components/detail-panel.tsx
  apps/report/src/components/open-in-playground.tsx
  apps/report/src/components/playground.tsx
  apps/report/src/components/report-overview.tsx
  apps/report/tsconfig.json
  package.json
  packages/android-playground/package.json
  packages/android-playground/tsconfig.json
  packages/android/src/device.ts
  packages/playground/src/adapters/base.ts
  packages/playground/src/adapters/local-execution.ts
  packages/playground/src/adapters/remote-execution.ts
  packages/playground/src/common.ts
  packages/playground/src/index.browser.ts
  packages/playground/src/index.ts
  packages/playground/src/sdk/index.ts
  packages/playground/src/server.ts
  packages/playground/src/types.ts
  packages/playground/tests/README.md
  packages/playground/tests/setup.ts
  packages/playground/tests/unit/base-adapter.test.ts
  packages/playground/tests/unit/common.test.ts
  packages/playground/tests/unit/local-execution-adapter.test.ts
  packages/playground/tests/unit/playground-sdk.test.ts
  packages/playground/tests/unit/playground.test.ts
  packages/playground/tests/unit/remote-execution-adapter.test.ts
  packages/playground/vitest.config.ts
  packages/visualizer/package.json
  packages/visualizer/src/component/playground/ContextPreview.tsx
  packages/visualizer/src/component/playground/FormField.tsx
  packages/visualizer/src/component/playground/PromptInput.tsx
  packages/visualizer/src/component/playground/ServiceModeControl.tsx
  packages/visualizer/src/component/playground/playground-execution.ts
  packages/visualizer/src/component/playground/playground-utils.ts
  packages/visualizer/src/component/playground/types.ts
  packages/visualizer/src/component/playground/useServerValid.ts
  packages/visualizer/src/index.tsx
  packages/visualizer/tsconfig.json
  packages/web-integration/package.json
  packages/web-integration/src/bin.ts
  packages/web-integration/src/index.ts
  packages/web-integration/src/static/index.ts
  packages/web-integration/src/static/static-agent.ts
  packages/web-integration/src/static/static-page.ts
  packages/web-integration/src/web-element.ts
  packages/web-integration/tests/ai/web/static/static-page.test.ts
  packages/web-integration/tests/unit-test/playground-server.test.ts
  packages/web-integration/tsconfig.json
  pnpm-lock.yaml
Labels: change: feat

#1164 fix(mcp): mcp should declare deps photon
  packages/mcp/package.json
  pnpm-lock.yaml
Labels: change: fix

#1171 feat(core): add hook for action space
  apps/site/docs/en/api.mdx
  apps/site/docs/zh/api.mdx
  packages/core/src/agent/tasks.ts
  packages/core/src/device/index.ts
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/playwright/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/puppeteer/page.ts
  packages/web-integration/src/web-element.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
Labels: change: feat

#1170 feat(web): longpress and swipe gesture
  packages/core/src/agent/agent.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/device/index.ts
  packages/core/tests/unit-test/llm-planning.test.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/core/tsconfig.json
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/web-page.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
Labels: change: feat

#1180 fix(core): rect size for deepThink
  packages/core/src/agent/agent.ts
  packages/core/src/ai-model/common.ts
  packages/core/src/yaml/player.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/evaluation/tests/llm-planning.test.ts
  packages/web-integration/src/puppeteer/base-page.ts
Labels: change: fix

#1176 docs(core): init docs for custom interface
  apps/site/docs/en/awesome-midscene.md
  apps/site/docs/en/integrate-with-any-interface.mdx
  apps/site/docs/zh/awesome-midscene.md
  apps/site/docs/zh/integrate-with-any-interface.mdx
  apps/site/rspress.config.ts
Labels: change: docs

#1182 fix(core): deepthink params
  packages/core/src/ai-model/common.ts
  packages/core/tests/unit-test/utils.test.ts
Labels: change: fix

#1195 feat(playground): refactor playground components and SDK to support unique server IDs
  apps/android-playground/src/App.less
  apps/android-playground/src/App.tsx
  apps/android-playground/src/components/playground-panel/index.less
  apps/android-playground/src/components/playground-panel/index.tsx
  apps/chrome-extension/src/components/playground/index.less
  apps/chrome-extension/src/components/playground/index.tsx
  apps/chrome-extension/src/extension/popup/index.less
  apps/playground/package.json
  apps/playground/src/App.less
  apps/playground/src/App.tsx
  apps/playground/src/components/screenshot-viewer/index.tsx
  packages/android-playground/src/bin.ts
  packages/playground/package.json
  packages/playground/src/adapters/local-execution.ts
  packages/playground/src/adapters/remote-execution.ts
  packages/playground/src/launcher.ts
  packages/playground/src/sdk/index.ts
  packages/playground/src/server.ts
  packages/playground/tests/unit/local-execution-adapter.test.ts
  packages/shared/package.json
  packages/visualizer/src/component/history-selector/index.less
  packages/visualizer/src/component/history-selector/index.tsx
  packages/visualizer/src/component/playground-result/index.less
  packages/visualizer/src/component/playground-result/index.tsx
  packages/visualizer/src/component/prompt-input/index.less
  packages/visualizer/src/component/universal-playground/index.less
  packages/visualizer/src/component/universal-playground/index.tsx
  packages/visualizer/src/hooks/usePlaygroundExecution.ts
  packages/visualizer/src/hooks/usePlaygroundState.ts
  packages/visualizer/src/types.ts
  packages/web-integration/demo/playground.ts
  pnpm-lock.yaml
Labels: change: feat

#1194 fix(web): dblclick for playwright
  packages/web-integration/src/chrome-extension/page.ts
  packages/web-integration/src/puppeteer/base-page.ts
  packages/web-integration/src/web-page.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
Labels: change: fix

#1199 feat(playground): implement safeOverrideAIConfig for improved AI configuration handling across components
  apps/android-playground/src/App.tsx
  apps/chrome-extension/src/extension/popup/index.tsx
  apps/report/src/components/playground.tsx
  apps/report/src/components/playground/index.tsx
  packages/core/tests/unit-test/prompt/playwright-generator.test.ts
  packages/playground/src/server.ts
  packages/visualizer/src/component/service-mode-control/index.tsx
  packages/visualizer/src/hooks/useSafeOverrideAIConfig.ts
  packages/visualizer/src/index.tsx
Labels: change: feat

#1196 feat(core): agent add options useCache, replanningCycleLimit
  packages/core/src/agent/agent.ts
  packages/core/src/agent/tasks.ts
  packages/core/src/types.ts
Labels: change: feat

#1200 docs: release preview feature of customized-interface
  README.md
  README.zh.md
  apps/site/docs/en/choose-a-model.mdx
  apps/site/docs/en/common/troubleshooting-llm-connectivity.mdx
  apps/site/docs/en/integrate-with-any-interface.mdx
  apps/site/docs/en/model-provider.mdx
  apps/site/docs/zh/choose-a-model.mdx
  apps/site/docs/zh/common/troubleshooting-llm-connectivity.mdx
  apps/site/docs/zh/integrate-with-any-interface.mdx
  apps/site/docs/zh/model-provider.mdx
  apps/site/docs/zh/prompting-tips.md
  apps/site/rspress.config.ts
Labels: change: docs

#1205 feat(site): update v0.28 release notes with new features, optimizations, bug fixes, and documentation enhancements
  apps/site/docs/en/changelog.mdx
  apps/site/docs/zh/changelog.mdx
Labels: change: feat

#1206 fix(chrome-playground): enhance AI description generation with model config and improve element rectangle handling
  apps/chrome-extension/src/extension/recorder/utils.ts
  apps/chrome-extension/src/utils/eventOptimizer.ts
Labels: change: fix

#1208 docs(core): normalize all titles in document
  apps/site/docs/en/api.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/awesome-midscene.md
  apps/site/docs/en/blog-introducing-instant-actions-and-deep-think.md
  apps/site/docs/en/blog-programming-practice-using-structured-api.md
  apps/site/docs/en/blog-support-android-automation.mdx
  apps/site/docs/en/bridge-mode-by-chrome-extension.mdx
  apps/site/docs/en/caching.mdx
  apps/site/docs/en/changelog.mdx
  apps/site/docs/en/choose-a-model.mdx
  apps/site/docs/en/common/setup-env.mdx
  apps/site/docs/en/common/start-experience.mdx
  apps/site/docs/en/common/troubleshooting-llm-connectivity.mdx
  apps/site/docs/en/data-privacy.md
  apps/site/docs/en/faq.md
  apps/site/docs/en/index.mdx
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/integrate-with-any-interface.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/llm-txt.mdx
  apps/site/docs/en/mcp-android.mdx
  apps/site/docs/en/model-provider.mdx
  apps/site/docs/en/prompting-tips.md
  apps/site/docs/en/quick-experience-with-android.mdx
  apps/site/docs/en/quick-experience.mdx
  apps/site/docs/en/web-mcp.mdx
  apps/site/styles/index.css
Labels: change: docs

#1210 fix(core): coord offset for qwen
  packages/core/src/agent/utils.ts
  packages/core/src/ai-model/common.ts
Labels: change: fix

#1212 feat(core): show warning for non vl model
  packages/core/src/agent/agent.ts
  packages/shared/src/env/model-config-manager.ts
Labels: change: feat

#1215 docs(core): update contribution guide
  CONTRIBUTING.md
  packages/core/rslib.config.ts
Labels: change: docs

#1220 feat(core): implement single warning for non-VL model usage
  packages/core/src/agent/agent.ts
Labels: change: feat

#1228 fix(visualizer): enhance canvas resizing and update image dimensions handling
  packages/visualizer/src/component/player/index.tsx
  packages/visualizer/src/utils/replay-scripts.ts
Labels: change: fix

#1227 feat(report): allow rendering of test stats with zero dumps
  apps/report/src/components/report-overview/index.tsx
Labels: change: feat

#1229 fix(core): tip for onTaskStartTip
  packages/web-integration/src/bridge-mode/agent-cli-side.ts
Labels: change: fix

#1231 docs(core): set cache polify for deploy
  apps/site/build.sh
  apps/site/config_deploy.sh
  apps/site/docs/en/caching.mdx
  apps/site/docs/zh/caching.mdx
  apps/site/package.json
Labels: change: docs

#1235 feat(core): refine implementation of aiAction + ui-tar
  apps/report/src/components/detail-side/index.tsx
  packages/core/src/agent/agent.ts
  packages/core/src/agent/tasks.ts
  packages/core/src/ai-model/conversation-history.ts
  packages/core/src/ai-model/index.ts
  packages/core/src/ai-model/llm-planning.ts
  packages/core/src/ai-model/prompt/llm-planning.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/ai-model/ui-tars-planning.ts
  packages/core/src/types.ts
  packages/core/tests/ai/ui-tars-planning/plan-to-target.test.ts
  packages/core/tests/unit-test/conversation-history.test.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/core/tests/unit-test/prompt/prompt.test.ts
Labels: change: feat

#1241 fix(core): update fields in report
  apps/report/src/components/detail-side/index.tsx
Labels: change: fix

#1240 feat(report): control replay defaults via URL parameters
  apps/site/docs/en/faq.md
  apps/site/docs/zh/faq.md
  packages/visualizer/src/component/player/index.tsx
  packages/visualizer/src/store/store.tsx
Labels: change: feat, codex

#1242 feat(core): validate dumps are from Playwright tests in report overview
  apps/report/src/components/report-overview/index.tsx
Labels: change: feat

#1249 feat(core): enable thinking for vqa
  apps/report/src/components/detail-side/index.tsx
  packages/core/src/agent/agent.ts
  packages/core/src/agent/tasks.ts
  packages/core/src/ai-model/inspect.ts
  packages/core/src/ai-model/prompt/extraction.ts
  packages/core/src/yaml.ts
  packages/core/tests/unit-test/prompt/__snapshots__/prompt.test.ts.snap
  packages/web-integration/tests/unit-test/page-task-executor-waitFor.test.ts
Labels: change: feat

#1251 fix(package): adjust files field in package.json for ios and ios-playground
  packages/cli/tests/multi_yaml_android_scripts/twitter-auto-like.yaml
  packages/cli/tests/multi_yaml_ios_scripts/twitter-auto-like.yaml
  packages/ios-playground/package.json
  packages/ios/package.json
Labels: change: fix

#1253 docs(site): Add support for iOS automation and enhance documentation
  README.md
  README.zh.md
  apps/playground/src/App.tsx
  apps/site/docs/en/blog-support-android-automation.mdx
  apps/site/docs/en/blog-support-ios-automation.mdx
  apps/site/docs/en/changelog.mdx
  apps/site/docs/en/common/prepare-ios.mdx
  apps/site/docs/en/common/start-experience.mdx
  apps/site/docs/en/index.mdx
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/en/integrate-with-ios.mdx
  apps/site/docs/en/integrate-with-puppeteer.mdx
  apps/site/docs/en/quick-experience-with-ios.mdx
  apps/site/docs/public/android.png
  apps/site/docs/public/ios.png
  apps/site/docs/zh/blog-support-android-automation.mdx
  apps/site/docs/zh/blog-support-ios-automation.mdx
  apps/site/docs/zh/changelog.mdx
  apps/site/docs/zh/common/prepare-ios.mdx
  apps/site/docs/zh/common/start-experience.mdx
  apps/site/docs/zh/index.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-ios.mdx
  apps/site/docs/zh/quick-experience-with-ios.mdx
  apps/site/package.json
  apps/site/rspress.config.ts
  packages/core/src/yaml/player.ts
  pnpm-lock.yaml
Labels: change: docs

#1257 feat(ios): implement proper device pixel ratio detection
  apps/playground/src/App.tsx
  packages/android/src/device.ts
  packages/ios/src/device.ts
  packages/ios/src/ios-webdriver-client.ts
  packages/ios/tests/unit-test/device.test.ts
  scripts/dictionary.txt
Labels: change: feat

#1260 docs(yaml): add global agent configuration for aiActionContext
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
Labels: change: docs

#1268 fix(core): aiWaitFor ut
  packages/web-integration/tests/unit-test/agent.test.ts
Labels: change: fix

#1271 feat(android): add runAdbCommand method to AndroidAgent
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  packages/android/src/agent.ts
Labels: change: feat

#1272 fix(agent): validate cache strategy configuration
  apps/site/docs/en/caching.mdx
  apps/site/docs/zh/caching.mdx
  packages/core/src/agent/agent.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/tests/unit-test/agent.test.ts
Labels: change: fix
