Repository web-infra-dev/midscene, pull requests merged in 2025-06, with the labels that each got.

#798 fix(cache): allow cache files to be stored in folders to enhance the cache
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/tests/unit-test/task-cache.test.ts
  packages/web-integration/tests/unit-test/util.test.ts
Labels: change: fix

#802 docs: optimize README.md video
  README.md
Labels: change: docs

#804 fix(core): update test cases
  packages/web-integration/tests/ai/web/playwright/ai-online-order.spec.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
  packages/web-integration/tests/ai/web/puppeteer/query.test.ts
Labels: change: fix

#807 docs(site): changelog for 0.17.4
  apps/site/docs/en/API.mdx
  apps/site/docs/en/changelog-0.17.4.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/changelog-0.17.4.mdx
  apps/site/rspress.config.ts
  packages/core/src/types.ts
Labels: change: docs

#811 docs(site): update gemini example
  apps/site/docs/en/choose-a-model.mdx
  apps/site/docs/zh/choose-a-model.mdx
Labels: change: docs

#812 feat(visualizer): support download video for player
  apps/report/src/App.tsx
  packages/visualizer/src/component/player.tsx
Labels: change: feat

#814 feat(report): add tooltip for download button
  packages/visualizer/src/component/player.tsx
Labels: change: feat

#820 fix(cli): deal with locate item in yaml
  packages/core/src/ai-model/ui-tars-planning.ts
Labels: change: fix

#826 feat(web-integration): support unstableLogContent api for agent
  apps/report/src/components/detail-side.tsx
  apps/site/docs/en/API.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  biome.json
  packages/core/src/ai-model/action-executor.ts
  packages/core/src/ai-model/service-caller/index.ts
  packages/core/src/insight/utils.ts
  packages/core/src/types.ts
  packages/core/src/utils.ts
  packages/core/src/yaml.ts
  packages/evaluation/tests/screenspot-v2-evaluation.test.ts
  packages/web-integration/modern.config.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/ai/web/playwright-reporter-test/todo-report.spec.ts
  packages/web-integration/tests/playwright.config.ts
  packages/web-integration/tests/unit-test/__snapshots__/agent.test.ts.snap
  packages/web-integration/tests/unit-test/agent.test.ts
  packages/web-integration/tests/unit-test/fixtures/dump.json
  packages/web-integration/tests/unit-test/plan-builder.test.ts
  packages/web-integration/tests/unit-test/util.test.ts
  packages/web-integration/tests/unit-test/yaml/player-rightclick.test.ts
  packages/web-integration/tests/unit-test/yaml/player.test.ts
Labels: change: feat

#818 feat(mcp, shared, visualizer): add license
  apps/site/docs/en/integrate-with-playwright.mdx
  apps/site/docs/zh/integrate-with-playwright.mdx
  packages/mcp/package.json
  packages/shared/package.json
  packages/visualizer/package.json
Labels: change: feat

#819 feat(cli): support dotenv-override argv for cli
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  packages/cli/src/cli-utils.ts
  packages/cli/src/index.ts
Labels: change: feat

#830 docs(site): fix code block formatting in playwright integration guide
  apps/site/docs/en/integrate-with-playwright.mdx
Labels: change: docs

#829 fix(core): only replace script tag
  apps/report/src/App.tsx
  apps/report/src/index.tsx
  nx.json
  packages/core/package.json
  packages/core/src/utils.ts
  packages/shared/src/utils.ts
  packages/web-integration/tests/ai/web/puppeteer/e2e.test.ts
  pnpm-lock.yaml
Labels: change: fix

#835 feat(web-integration): dump pageContext for aiAssert
  packages/web-integration/src/common/tasks.ts
Labels: change: feat

#839 feat(android): support ime strategy for android device
  apps/site/docs/en/integrate-with-android.mdx
  apps/site/docs/zh/integrate-with-android.mdx
  nx.json
  packages/android/src/agent/index.ts
  packages/android/src/page/index.ts
  packages/shared/src/env.ts
Labels: change: feat

#837 fix(shared): add text content for leaf elements before text node
  biome.json
  packages/core/src/ai-model/prompt/util.ts
  packages/core/tests/fixtures/dump-for-utils-test.json
  packages/core/tests/unit-test/prompt/utils.test.ts
  packages/shared/src/extractor/locator.ts
Labels: change: fix

#844 feat(web-integration): support user expected xpath option for locate methods
  apps/report/src/components/detail-side.tsx
  apps/report/src/components/sidebar.tsx
  apps/site/docs/en/API.mdx
  apps/site/docs/en/automate-with-scripts-in-yaml.mdx
  apps/site/docs/zh/API.mdx
  apps/site/docs/zh/automate-with-scripts-in-yaml.mdx
  nx.json
  packages/core/src/types.ts
  packages/core/src/yaml.ts
  packages/core/tests/unit-test/executor/index.test.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/task-cache.ts
  packages/web-integration/src/common/tasks.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/yaml/player.ts
  packages/web-integration/tests/ai/web/puppeteer/open-new-tab.test.ts
Labels: change: feat

#848 docs(site): add availability notes for web-only methods
  apps/site/docs/en/API.mdx
  apps/site/docs/zh/API.mdx
Labels: change: docs

#861 fix(core): replace dirty json due AGPL license
  packages/core/package.json
  packages/core/src/ai-model/service-caller/index.ts
  pnpm-lock.yaml
Labels: change: fix

#854 feat(report): each time, append the report individually instead of appending in bulk to avoid excessive memory usage
  apps/chrome-extension/src/extension/misc.tsx
  apps/report/src/App.tsx
  apps/report/src/index.tsx
  apps/report/src/types.ts
  apps/report/template/index.html
  apps/report/test-data/ai-shop.json
  packages/core/src/utils.ts
  packages/core/tests/unit-test/utils.test.ts
  packages/web-integration/src/common/agent.ts
  packages/web-integration/src/common/utils.ts
  packages/web-integration/src/playground/server.ts
  packages/web-integration/src/playwright/ai-fixture.ts
  packages/web-integration/src/playwright/reporter/index.ts
  packages/web-integration/tests/ai/web/playwright/memory-release.spec.ts
  packages/web-integration/tests/playwright.config.ts
  packages/web-integration/tests/unit-test/fixtures/web-extractor/input.png
  packages/web-integration/tests/unit-test/fixtures/web-extractor/output.png
Labels: change: feat

#867 docs(site): 0.20 changelog
  apps/site/docs/en/changelog.mdx
  apps/site/docs/zh/changelog.mdx
Labels: change: docs
